### ISSUE TITLE
Validation not working when using ng-model-options="{ getterSetter: true }" 

### ISSUE THREAD

**Issue by smsahu** [huei90/angular-validation#103]
Hi,
Validation is working for simple ng-model but not when used with ng-model-options

Please find the reference code:
http://plnkr.co/edit/Ipjll1?p=preview

**Comment by huei90** [comment]
Sorry @smsahu 
This version doesn't support ng-model-options yet. Are you super need for this feature?

**Comment by Alex-Cosma** [comment]
Any word on this? :+1:

**Comment by huei90** [comment]
not yet.
 Do you have any idea how angular-validation use ng-model-options?

**Comment by huei90** [comment]
Hi @smsahu @Alex-Cosma I have checked the api
https://code.angularjs.org/1.3.20/docs/api/ng/directive/ngModelOptions

Do you mind show your case using model-model-options in gettersetter true without angular-validation first?

**Comment by elpdpt** [comment]
I work on enterprise angularjs project. It seems this is still relevant. From debugging its coming from using `scope.$eval(ngModel)`. For anyone interested, my solution was to use `Object.defineProperty` to define a model with get/set properties that can replace the getterSetter functionality.
