### ISSUE TITLE
Will this handle strings as numbers?

### ISSUE THREAD

**Issue by npearson72** [huei90/angular-validation#105]
I need to display floats with .00

The problem with the number input type is that it cuts off those decimals, leaving me with numbers like:

4.15
4.1
4

This looks pretty inconsistent in my forms, and is not a good representation of money -- which is what I need.

If I use a standard input field that isn't a number type, it looks fine but does not get validated for numbers.

Is this possible to do? Is there a way to add parseFloat to the number validator?

Thanks

**Comment by huei90** [comment]
You need set your own validation expression.

See https://github.com/huei90/angular-validation/blob/master/API.md#setup-a-new-validation-setexpression-setdefaultmsg-with-regexp-or-function-in-config-phase
