### ISSUE TITLE
replace grunt with gulp

### ISSUE THREAD

**Issue by kcliu** [huei90/angular-validation#107]
for speed up and easier maintenance

**Comment by huei90** [comment]
Yes. But I won't do that until I need that =)

**Comment by huei90** [comment]
Close it. Open if needed.

**Comment by kcliu** [comment]
haha I can do that for u

**Comment by huei90** [comment]
hmmmm... But I see no benefit on this change.

**Comment by kcliu** [comment]
it's ok

**Comment by huei90** [comment]
I need some help on demo.html documentation. Its not yet complete, more example, UI, API document.

It will be great if you can help me on that XD
