### ISSUE TITLE
Completely disabling validation

### ISSUE THREAD

**Issue by rreeve07** [huei90/angular-validation#108]
I would like to be able to completely remove validation in certain cases.

For example: I want to enable an input based on another input; however, I also want to disable the validation on the disabled input. http://plnkr.co/edit/RO1n8j4ABQ5iZVq9EdqV?p=preview

Is there any way to do this?

**Comment by huei90** [comment]
Try `no-validation-message`

https://github.com/huei90/angular-validation/blob/master/API.md#dont-show-the-valid-message-no-validation-messagetrue

See if this works.

**Comment by rreeve07** [comment]
That doesn't appear to work at all. Setting no-validation-message="true" does not stop the submit button from validating the field (it also displays the validation message).

http://plnkr.co/edit/RO1n8j4ABQ5iZVq9EdqV?p=preview

**Comment by huei90** [comment]
Try
```html
<input id="testB" name="testB" class="form-control" ng-model="testBModel" validator="required" no-validation-message="{{!testAModel}}" ng-disabled="!testAModel"/>
```

 use `{{!testAModel}}`

**Comment by rreeve07** [comment]
That also does not work. The submit button still causes validator to run on the input regardless of ```no-validation-message```.
```html
<button class="btn btn-primary" validation-submit="form">Submit</button>
```

**Comment by huei90** [comment]
Seems you need the `valid-method` check that.

**Comment by rmngrc** [comment]
The no-validation-message directive is not working for me as well. In my HTML I have:

```html
<input type="text" id="contactEmail" name="contactEmail" class="form-control" ng-model="contactDetails.email" validator="required, email" no-validation-message="true" />
```

But the error message is still showing up and the form can't be submitted. It seems to be a bug in the project.

**Comment by rmngrc** [comment]
@rreeve07 @huei90 

I've created a new PR with the fix of this issue. See https://github.com/huei90/angular-validation/pull/131 for further details :)

Cheers,

**Comment by huei90** [comment]
Fix.
