### ISSUE TITLE
v1.3.1 & v1.3.0  not showing multiselect validation error

### ISSUE THREAD

**Issue by MayankLogiciel** [huei90/angular-validation#112]
I updated to v.1.3.0 & v1.3.1 from v.1.2.6 and now validation on html multi select  not wokring though it continue to work on html single select as earlier.

When i reverted back to v1.2.6 html multi select and single select validation working fine.

**Comment by huei90** [comment]
Sorry for the late reply. I will try to look for it this few days.

**Comment by huei90** [comment]
@MayankLogiciel Do you mind showing your multi select validation code to me?

**Comment by MayankLogiciel** [comment]
I wasn't able to revert back to that state. Since then we have changed a lot of things. Also we have made custom multi select due to some other crashing issue with some android versions.

I quickly tried to test multi select validation and now validations are working fine with v.1.3.1.

Thanks for your time and work. I really appreciate your effort.
