### ISSUE TITLE
Error with AngularUI datepicker

### ISSUE THREAD

**Issue by mpanichella** [huei90/angular-validation#113]
When i add validation to AngularUI Datepicker, i have an error that say

Error: [$compile:multidir] Multiple directives [datepickerPopup, validator] asking for new/isolated scope on: <input name="VigenciaDesde" class="form-control ng-pristine ng-untouched ng-valid" type="text" data-ng-model="poliza.VigenciaDesde" validator="required" valid-method="watch" is-open="openedDesde" close-text="Close" data-datepicker-popup="dd/MM/yyyy">

**Comment by huei90** [comment]
Hi Would you mind giving me a short demo (plunkr or jsbin) for it?

**Comment by mpanichella** [comment]
Hi, i have a big project created in VisualStudio, when i finish this project i can send you an example.
But if you want, only add the validator to AngularUI Datepicker, and you can see the error. Thank you very much for your fast response.

**Comment by huei90** [comment]
Ok I will try it. list at bug.

**Comment by mpanichella** [comment]
thank you very much. One question, is possible to add validation conditional? for example, if i check a radiobutton validate x field but if i check other radio validate different in same form

**Comment by mpanichella** [comment]
Something new with this error?

**Comment by huei90** [comment]
Sorry @mpanichella not yet :cry:

**Comment by josearodrigueze** [comment]
How can we resolve the collision policy? power by Google Translate
Code in plunker
http://plnkr.co/edit/7WvMsv?p=preview

**Comment by huei90** [comment]
I have no solution for this.
We can't have multiple directive for the input =(

http://stackoverflow.com/questions/27485848/why-cant-multiple-directives-ask-for-an-isolated-scope-on-the-same-element

**Comment by Nazanin1369** [comment]
@huei90  I am working on this issue Huei. I was able to remove the isolated scope and make it work for the $watch. Currently I am working on other type of validation.

**Comment by huei90** [comment]
Ok sure. Open.

**Comment by Nazanin1369** [comment]
Now actually all the validation are working fine, I just need to verify couple of more things and will let u know to have a code review

**Comment by huei90** [comment]
Thank you @Nazanin1369 look forward to see that.

**Comment by Nazanin1369** [comment]
​Now the datepicker is working. There is only one issue with demo html
file. Since u r using Foundation css the bootstrap datapicker is not styled
properly. We have to use bootstrap css.​ What do u think?

Best Regards,

**Comment by huei90** [comment]
Hi @Nazanin1369 
We do have a demo link for bootstrap
http://plnkr.co/edit/rjIIkX

Do you mind edit it on plunker?

**Comment by Nazanin1369** [comment]
​That is fine but the plunker does not have my local changes for testing
before push. Do you want me to refactor the demo page to bootstrapUI?​

Best Regards,

**Comment by huei90** [comment]
Don't need to refactor the demo page.
You can create another page name `demo-bootstrap.html`.

**Comment by huei90** [comment]
@Nazanin1369 I would like to see your solution.

**Comment by huei90** [comment]
I'm not focus on this fix now, need contribution.

**Comment by FuGardenia** [comment]
@Nazanin1369 @huei90  Hi, is the bug solved ?

**Comment by huei90** [comment]
We will fix it within few days. Stay tuned @FuGardenia

**Comment by Nazanin1369** [comment]
Yes, I believe it merged to master,
