### ISSUE TITLE
type="number" validator="number,maxlength=4" 

### ISSUE THREAD

**Issue by think2011** [huei90/angular-validation#114]
it's bug when type="number"?
```
<input type="number" name="number" ng-model="form.required" 
              validator="number,maxlength=4"  />
```

![](http://s1.momo.moda/2015/05/29/daca41214b39c5dc66674d09081940f0.gif)

**Comment by huei90** [comment]
hmmmm.. thanks for report this. I haven't tried anything in `type="number"` yet :hushed:

**Comment by think2011** [comment]
it's very powerful validation, thanks!😄

**Comment by sjmcpherso** [comment]
+1, this is important for UX in responsives site to give the correct input keyboard

Only seem to cause problems with a combination of validation maxlength and/or minlength and type="number" i.e. input[type=email], input[type=tel], input[type=name] all work correctly and type="number" with 'required' and/or 'number' validations work fine as well

**Comment by huei90** [comment]
I have checked the problem.

Looks like using `type=number`, browser will get input only in number, given text is not pass to the value.

Also, we need some other more check in the `rule.js`

https://github.com/huei90/angular-validation/blob/master/src/rule.js#L16

for your reference.

**Comment by sjmcpherso** [comment]
Ok so you think its an issue due to a number being passed in as the value instead of a string?

I see the value passed into the minlength/maxlength expression is 'undefined'

minlength: function(value, scope, element, attrs, param) {
console.log(value) //returns 'undefined'

**Comment by huei90** [comment]
you are right. We need to special handle `minlength` in the `rule.js`

**Comment by sjmcpherso** [comment]
I haven't tested intensively but this seems to do the trick

                var checkValidation = function(scope, element, attrs, ctrl, validation, value) {
                    if(value) value = value.toString();  <--- addition
                    
                    var validators = validation.slice(0),

will do some more testing

**Comment by huei90** [comment]
hmmm.Sorry @think2011 @sjmcpherso I have currently no idea about this.

Seems browser has special handle for input text or number, should we detect it?

**Comment by huei90** [comment]
@think2011 @sjmcpherso Here's the fix.
Thanks for @hungdoan2 notified the possible bug.

And finally this fix the problem.

**Comment by huei90** [comment]
https://github.com/huei90/angular-validation/pull/140

**Comment by huei90** [comment]
Done, open if any problem.
