### ISSUE TITLE
How can I allow empty fields？

### ISSUE THREAD

**Issue by think2011** [huei90/angular-validation#115]
```
<form name="form">
    <input type="text" name="url" validator="url"  ng-model="url">

<button validation-submit="form" type="submit" ng-click="submit();">submit</button>
</form>
```
![](http://s1.momo.moda/2015/05/29/6e2713a6efee97bacb63e52c54f0ada0.gif)

If user not any input, i want allow to submit，can you give me a example？

**Comment by huei90** [comment]
You should customise your validation that null will pass.

**Comment by think2011** [comment]
Ok, I guess too，thanks！

**Comment by huei90** [comment]
:+1:

**Comment by wingwell** [comment]
try to comment file angular-validation.js line752  //return;
