### ISSUE TITLE
validation-submit="form"，want foucs to error input.

### ISSUE THREAD

**Issue by think2011** [huei90/angular-validation#116]
```
<button validation-submit="form" type="submit" ng-click="submit();">submit</button>
```

![](http://s1.momo.moda/2015/05/29/d1f491a404d6854880943e5c3cd9ca25.gif)

I just suggested, because the page may be very long :)

**Comment by huei90** [comment]
duplicate problem on focus 
https://github.com/huei90/angular-validation/issues/111

**Comment by huei90** [comment]
this is a good suggestion. thanks!
