### ISSUE TITLE
Looking for maintainer 

### ISSUE THREAD

**Issue by huei90** [huei90/angular-validation#118]
Currently looking for `angular-validation`'s maintainer.

If you interest on this, please drop me a message or email me.

Thanks. There are still lot of works to do to improve `angular-validation`

**Comment by Nazanin1369** [comment]
I am interested

**Comment by huei90** [comment]
Hi @Nazanin1369 Welcome =)

Currently support for angularjs1.2, and partly 1.3, you can find them on the branch tag v1.2.x, v1.3.x

Feel free to contribute the branch you like even you can create v1.4.x to support angularjs1.4

again, thank you for your interested :beers:

**Comment by Nazanin1369** [comment]
Sure Huei, Thanks

**Comment by lvarayut** [comment]
HI @huei90,  I'm willing to help.

**Comment by huei90** [comment]
Hi @lvarayut Good to see you. Which feature do you want to help on?

**Comment by lvarayut** [comment]
@huei90, could you list all features that you wish to have? I could pick up some of them!

**Comment by huei90** [comment]
Ok @lvarayut , I will do this on the board 1.3.x, 1.4.x.

Or you can start listing them by yourself.

**Comment by lvarayut** [comment]
Alright :beers:

**Comment by huei90** [comment]
Let's have some :beers:
