### ISSUE TITLE
How to validate multiple forms separately

### ISSUE THREAD

**Issue by ruslanchek** [huei90/angular-validation#119]
I have a few forms on a page, and submit one of them emits validation on all another, that have "ng-dirty" classes. How to avoid this case?

**Comment by huei90** [comment]
@ruslanchek How about separate the form?

**Comment by ruslanchek** [comment]
@huei90 What does it mean? The forms are separated, but placed in one page.

**Comment by huei90** [comment]
```html
<!-- Form1 -->
<form name="Form1">
        <div>
            <label>Required</label>
            <input type="text" name="required" ng-model="form1.required" validator="required">
        </div>
        <button validation-submit="Form1">Submit</button>
</form>

<!-- Form2 -->
<form name="Form2">
        <div>
            <label>Required</label>
            <input type="text" name="required" ng-model="form2.required" validator="required">
        </div>
         <button validation-submit="Form2">Submit</button>
</form>
```

How about this?

**Comment by ruslanchek** [comment]
@huei90 I have the same code. The forms are separated. But naven't validation-submit attribute, is the reason i think. Thx.

**Comment by huei90** [comment]
Would you mind post your form html here? I would like to help on debugging :smile:

**Comment by huei90** [comment]
Open it if having the issue again.
