### ISSUE TITLE
你好，我有个问题

### ISSUE THREAD

**Issue by qiuling2014** [huei90/angular-validation#120]
在使用时，我发现如何我加上一个校验的格式，该项就会变成必填项，这个如何处理？比如：我有一个telephone字段是个不必填项，只有当用户输入后才要去检查格式，但是我提交表单时，它会提示电话格式不对。

**Comment by huei90** [comment]
你好，調整你的 telephone regular expression / function ，允許不是必填就可以了

**Comment by qiuling2014** [comment]
thank you very much, best wish for you.

**Comment by huei90** [comment]
有問題隨時發文 :+1:
