### ISSUE TITLE
你好，我还有个问题

### ISSUE THREAD

**Issue by qiuling2014** [huei90/angular-validation#121]
能不能让$validationProvider.checkValid方法只检测必填项的...现在它连不必填也会检测

**Comment by huei90** [comment]
你可以 － Customizable Initial Validation
https://github.com/huei90/angular-validation/blob/master/API.md#customizable-initial-validation

讓你參考

**Comment by qiuling2014** [comment]
thank you very very much, you art good man,best wish to you.

**Comment by huei90** [comment]
:beers:
