### ISSUE TITLE
Not recognizing styled select dropdowns

### ISSUE THREAD

**Issue by jamesparasole** [huei90/angular-validation#123]
Great job...have been able to implement this pretty easily. However, I ran into one issue. When using jquery to style select dropdown options (like below image), this validator is not recognizing when an option is selected. Added "ignore: ':hidden:not(:select)'", but still no go. My select code is:

<select  id = "selectdropdown" name = "selectdropdown" ng-model = "form.selectdropdown"  required-message = "'Lorem Ipsum'" required>

Any thoughts?

![image](https://cloud.githubusercontent.com/assets/4148461/8371322/fdcb7052-1ba3-11e5-9e34-0e7703a3a55d.png)

**Comment by huei90** [comment]
?? where's the code.

**Comment by jamesparasole** [comment]
The dropdown styling is from here: http://jsfiddle.net/BB3JK/47/

The validation is from here: http://plnkr.co/edit/XbDYKrM2QUf8g1ubTHma?p=preview

**Comment by huei90** [comment]
@jamesparasole I'm not really understand the demo you gave me.
