### ISSUE TITLE
disunion validation on "model change" vs on "submit a form"

### ISSUE THREAD

**Issue by hungdoan2** [huei90/angular-validation#128]
I write a custom model binder 
Example: 
Model value = 1000000 < bind to view > View Value = 1,000,000
and
View Value = 1,000,000 < bind to model> Model value = 1000000 

When I'm typing some thing in the input. I got valid validation ( because of value = 1000000)
but 
When I submit the form. I got invalid validation ( because of value = 1,000,000)

Look at your code, I get this: 

**On submit validation: **
```
scope.$on(ctrl.$name + 'submit-' + uid, function(event, index) {
   var value = ctrl.$viewValue,
    isValid = false;

    isValid = checkValidation(scope, element, attrs, ctrl, validation, value);
  .......
```
**=> When submit, Validator get value from $viewValue**

**But when model change (default behavior):**
```
scope.$watch('model', function(value) {
                                /**
                                 * dirty, pristine, viewValue control here
                                 */
                                if (ctrl.$pristine && ctrl.$viewValue) {
                                    // has value when initial
                                    ctrl.$setViewValue(ctrl.$viewValue);
                                } else if (ctrl.$pristine) {
                                    // Don't validate form when the input is clean(pristine)
                                    if (scope.messageId)
                                        angular.element(document.querySelector('#' + scope.messageId)).html('');
                                    else
                                        element.next().html('');
                                    return;
                                }
                                checkValidation(scope, element, attrs, ctrl, validation, value);
                            });
```

**=> Validator get value from model**

**So, Is there something wrong here ?**

**Comment by huei90** [comment]
Do you mean that your value will be `1,000,000` instead of `1000000` and can't pass the validation?

**Comment by wutgit** [comment]
Hello!

I have actually ran into exact same problem too, when i started using $parsers/$formatters.

The problem is, as hungdoan2 described, that when clicking submit, $viewValue is sent to validator, while when changing value in UI, the model value is used.

For his example, 

1. When clicking submit, $viewValue=1,000,000 and it is sent to validator (check on submit section).
2. When typing something into control, model change triggers, and the value there is the model value with value=1000000.

For my own needs, for example, i would really like to have both $viewValue and modelValue in the validator function. Or, another possiblity, is to pass ctrl to validation function, so that then we can just ctrl.$viewValue and use it for validation, if needed.

**Comment by huei90** [comment]
Hi @hungdoan2 @wutgit I have no problem on that.
Would you show me the example and I can test for that.

**Comment by hungdoan2** [comment]
@huei90 This is what I have used in my product. I hope this will help.
http://plnkr.co/edit/FTI6yy

**Comment by huei90** [comment]
Hi @hungdoan2 Thanks for the link.

the value change because of `base-editors-textnumber="0"`, you can update the number expression to allow `,`.
Then everything will be fine. :smile:

**Comment by huei90** [comment]
```js
(function () {
    var app = angular.module('myApp', ['validation', 'validation.rule','base.editors']);
    app.controller('index', ['$validation',function($validation){
      $validation
                .setExpression({
                    number: /\d+/
                })
    }]);
}).call(this);
```
This looks good to me.

**Comment by hungdoan2** [comment]
@huei90 yes, That is what I've done in my end.
But as I mention above.  The problem is that the validation express received different `value` in `different events`.
+ `value` will be `model value` on `model change event`
+ `value` will be `view value` on `form submit event`

=> It will reduce the `consistency` of your apis,=> We'll able to make more mistake.

So,I think, It's better to have both $viewValue and modelValue in the validator function, or you just pass the model value only.

**Comment by huei90** [comment]
Somehow I finally got your point.

model change event <br/>
https://github.com/huei90/angular-validation/blob/master/src/directive.js#L274

ctrl.$viewValue <br/>
https://github.com/huei90/angular-validation/blob/master/src/directive.js#L253-L256

One is using model change `value` but one using the `ctrl.$viewValue`,
we should choose only one. Am I right?

**Comment by hungdoan2** [comment]
@huei90  yes, That is what I'm going to tell ^^.

**Comment by huei90** [comment]
:+1: Thanks for reporting this. It's a very critical problem :beers: I will fix it.

**Comment by huei90** [comment]
Hi @hungdoan2 
Here's the change, please take a look for the pr.
https://github.com/huei90/angular-validation/pull/140

**Comment by huei90** [comment]
Done. Open it if any problem.
