### ISSUE TITLE
inValidCallback in bower package

### ISSUE THREAD

**Issue by pyalxx** [huei90/angular-validation#130]
Hi,

When installing with bower I still have inValidCallback in dist/angular-validation.js, though I can see that it is fixed in current version.

Please, let me know if I'm doing something wrong, thanks!

**Comment by huei90** [comment]
@pyalxx I'm not really understand your issue.
Is inValidCallback available to you?

**Comment by pyalxx** [comment]
@huei90, here is the full the scenario:

- I've cleared a bower cache to be sure
- I've installed bower package using bower install angular-validation --save
- 1.3.1 version installed
- when I browse bower_components/dist/angular-validation.js it still contains:

if (scope.inValidCallback) scope.inValidCallback(); 

Therefore invalid-callback is not working. I had to change this line and include script separately to make it work.

**Comment by huei90** [comment]
Hi @pyalxx Sorry for the late reply.

Do you mean this?
https://github.com/huei90/angular-validation/blob/master/dist/angular-validation.js#L361

should be `scope.invalidCallback`,

we have some mistake on using `inValidCallback` and `invalidCallback`, we have fix this on this commit
https://github.com/huei90/angular-validation/commit/bf95088c673c11fd3fba6139e67af8259ed2fc1d

**Comment by pyalxx** [comment]
Hi @huei90,

Thanks for reply. Yes, exactly. 

But for some reason version that was provided by bower contained previous code (with inValidCallback). Therefore I've switched to manual inclusion of script into my projects.

I've just checked and installed with bower install and it is still the same in 1.3.1

**Comment by huei90** [comment]
Hi @rmngrc , 

I have checked that, 1.3.1 still using the old one `inValidCallback`

I will update it to 1.3.2 later, and there will be the `invalidCallback`

Sorry for this inconvenient :+1:

**Comment by huei90** [comment]
Done, you can download the latest code on bower using version 1.3.2 now :beers:
