### ISSUE TITLE
Any way to validate the form outside of the form scope?

### ISSUE THREAD

**Issue by j-langlois** [huei90/angular-validation#134]
First of all, thanks for the great module. One of the best out there.
So I have this multi-step form where there are navigable links for on top. However, these links are outside of the current form scope. I was wondering if there would be a way I could get the form object outside of the form scope to validate it from a controller  e.g.

![snap4](https://cloud.githubusercontent.com/assets/13194485/9288507/8b8bcf46-4317-11e5-9080-11cc672bf5c5.jpg)

```javascript
//state transition using nav links
$rootScope.$on('$stateChangeStart', 
    function(event, toState, toParams, fromState, fromParams) {
    // Get form object
    var form = <something>
    $scope.form.submit(form);
    if (!form.checkValid(form)) {
       //prevent state change
        event.preventDefault();
});
```

Or any other suggestion would be welcome.
Thanks again

**Comment by Nazanin1369** [comment]
You can have a service which is responsible to change the state and inject it into your form scope controller and to your toolbar. 
As you put the form in the $scope variable another way(but not so good) is to access the $parent scope from the $scope.$parent and authorize the state change.

**Comment by huei90** [comment]
@Nazanin1369 is right.
You are suggest to wrap them in the `<Form>`, in your case, broadcast may be the better solution.

**Comment by huei90** [comment]
@j-langlois Get broadcast works?

**Comment by j-langlois** [comment]
Dear friends,
I did not get broadcast to work but followed your suggestion and wrapped my toolbar inside the form, now it works but every form has the same form name, which is no problem for now. Thanks for the help!

**Comment by huei90** [comment]
Great, cool.

Great to hear that :beers:

**Comment by poppahorse** [comment]
For my use case it is not possible to wrap inside the <form>, @huei90 any other ideas to get this working outside the form?

**Comment by huei90** [comment]
unfortunately no, `angular-validation` only works when you wrap inside the form.

**Comment by poppahorse** [comment]
Hmm, not even possible with a service as @Nazanin1369 mentioned?

**Comment by huei90** [comment]
Can you point which service do you mean?

**Comment by poppahorse** [comment]
I have form submission happening from a common header file, as such its not possible to have the submit button within the actual form. The service is just a custom one I am using to allow each controller to configure the header to have the appropriate actions / buttons etc

**Comment by huei90** [comment]
try broadcast.

it's ugly and they are not in the same form,

**Comment by poppahorse** [comment]
ok thanks, I will have a play
