### ISSUE TITLE
angularjs 1.4.7 support

### ISSUE THREAD

**Issue by huei90** [huei90/angular-validation#137]
Need contribution.

**Comment by lvarayut** [comment]
Could you list all features that you wish to develop? I could pick up some of them.

**Comment by lvarayut** [comment]
This is the list of enhancements:

Priority  | Subject | Assignee
:-------------: | ------------- | -------------
High  | Support checkbox and radio button (#40) | @Nazanin1369 
High | Fix multidir error when using with another directive  (#95 and #113) | @lvarayut
Medium | Improve the HTML  documentation: Move API.md and Q&A.md to their own HTML pages,  Organize the documentation to be more beautiful |
Low | Make a logo and put it into the README.md | 
High |  Support AngularJs 1.4.x (#137) | 
Low  | Rewrite everything in ES6 or Typescript (Optional) |
Low  |  Prepare for upcoming AngularJs 2.0  |

**Comment by huei90** [comment]
New issue.
Support ng-repeat in angular-validation version 1.2.x
https://github.com/huei90/angular-validation/issues/139

**Comment by huei90** [comment]
Refactor new documentation. It is not easy to read now.

**Comment by kmckee** [comment]
Has anyone tried using this library with 1.4?  

We are looking to migrate next week.  I was just about to pull this library in to our app, but I don't want to if it will be broken when we move to 1.4.

**Comment by huei90** [comment]
Hi @kmckee Thanks for dropping us a message.

Unfortunately, the test result running on angular 1.4 in current validation version is fail.

We are still trying hard to move the support version to the latest one. Please stay tuned.

@lvarayut @Nazanin1369 seems we have lot of works to do now :beers:

**Comment by kmckee** [comment]
Thanks for the quick reply @huei90.  I might peek under the covers if I get some time and see if I can help out.  Very cool library, it cleaned up a lot of boring boiler plate code from our codebase.

**Comment by huei90** [comment]
>  it cleaned up a lot of boring boiler plate code from our codebase.
Yes, this is the main purpose why I'm building angular-validation :+1:

**Comment by edriang** [comment]
I have the following questions in order to decide to use or not this great module:
- Wich are the problems with Angular 1.4? 
- It is possible to integrate i18n messages with angular-translate module?

Thanks in advance

**Comment by huei90** [comment]
Hi @edriang 
First, we are not yet fully support angular 1.4
Secondly, for the i18n, see if this works to you and I can help you on that.
https://github.com/huei90/angular-validation/issues/96

**Comment by huei90** [comment]
OMG.. angular 1.5 is coming. :fire:

**Comment by huei90** [comment]
@kmckee Sorry for the late replied. v1.4.x is now ready! :boom: 

you can use it now. remember change the branch to v1.4.x

**Comment by Nazanin1369** [comment]
Congrats! Tests passed with Angular1.4.x. 
Change confirmed. closing this issue.

@lvarayut Can you move the enhancement list out of this issue?

**Comment by huei90** [comment]
:beers:

**Comment by huei90** [comment]
I have change the title to **Ticket and Enhancement**
https://github.com/huei90/angular-validation/issues/174
