### ISSUE TITLE
It is not working with bootstrap input-groups

### ISSUE THREAD

**Issue by rc125** [huei90/angular-validation#142]
Validation message is breaking bootstrap-input groups.

http://plnkr.co/edit/KFrGbvDNQlZZlN1w3D2t?p=preview

**Comment by lvarayut** [comment]
You could use `message-id` attribute to solve it. Please take a look at the example in the [API](https://github.com/huei90/angular-validation/blob/master/API.md#use-a-custom-valid-message-).

**Comment by huei90** [comment]
Also, you can refer to **Integrating with Twitter Bootstrap section**
https://github.com/huei90/angular-validation#integrating-with-twitter-bootstrap

**Comment by lvarayut** [comment]
I'm closing the issue. Feel free to ask if you were still facing the problem.
