### ISSUE TITLE
required 验证方式遇到value为数字0的时候无法通过验证

### ISSUE THREAD

**Issue by mingjunyang** [huei90/angular-validation#146]
当我的id设置为0 的时候，这个验证通不过。

```html
<input message-id="message-store" name="store" ng-model="form.store.id" type="hidden" validator="required">
```

```javascript
//建议使用正则验证
//  /^.*[^\s]+.*$/
required: function(value) {
    return !!value;
},
```

**Comment by lvarayut** [comment]
@huei90

**Comment by huei90** [comment]
@mingjunyang You are free to custom the `required` rule in your project :smile:

**Comment by mingjunyang** [comment]
我自己的项目已经通过自定义验证规则的方式绕过这个坑了嘛， 0 值通不过 `required`验证的确有点吓人。

**Comment by huei90** [comment]
![screen shot 2015-10-24 at 1 00 13 am](https://cloud.githubusercontent.com/assets/2560096/10699608/84f1d3a6-79ea-11e5-9e2a-a548ba081904.png)

我沒這個問題耶

目前 validate 是把 int 0 轉換成 string 0,

所以 !!"0" => True

**Comment by huei90** [comment]
不過確實，原本使用 !!value 有可能發生這類 falsy 的問題

**Comment by mingjunyang** [comment]
弱类型的语言，没有强制类型检查，形式上正确但是逻辑上有错误的问题比较容易发生，正好我们就碰上了。

**Comment by huei90** [comment]
沒有辦法～未來如果使用 angular2.0 採用 TypeScript 就可以支援強類型了
