### ISSUE TITLE
invalid callback invoke problem

### ISSUE THREAD

**Issue by pyalxx** [huei90/angular-validation#151]
Hello again, 

I'm still having problems with invalid callback. 

The reason of using this package is to simplify the validation of specific fields, but I try to use custom notification directive to show error. As per documentation I've disabled error and success messages (my full config):

```javascript
var expression = {
 email: /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,64}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,64}[a-zA-Z0-9])?)*$/
};

$validationProvider.setExpression(expression);
$validationProvider.showSuccessMessage = false;
$validationProvider.showErrorMessage = false;
```

It still tries to get error message. My html:

```html
<form class="form-step_content_form" name="homeForm" novalidate>
    <input class="form-step_content_form_field"
           name="email"
           type="email"
           placeholder="Your email"
           autocomplete="off"
           ng-model="user.email"
           validator="email"
           valid-method="submit-only"
           invalid-callback="setNotification(1, 'Email is invalid')">
    <button class="form-step_content_form_button form-step_content_form_button_icon form-step_content_form_button_icon_submit"
            ng-if="user.email.length > 0"
            validation-submit="homeForm">
    </button>
</form>
```
setNotification is a rootScope function which is also accessible and tested. 

I know where is the problem, if you look into angular-validation.js you'll see this:

```javascript
var invalidFunc = function(element, validMessage, validation, scope, ctrl) {
      var messageToShow = validMessage || $validationProvider.getDefaultMsg(validation).error;
      var messageElem;

      if (scope.messageId) messageElem = angular.element(document.querySelector('#' + scope.messageId));
      else messageElem = element.next();

      if ($validationProvider.showErrorMessage && messageToShow) {
        messageElem.html($validationProvider.getErrorHTML(messageToShow));
      }

      ctrl.$setValidity(ctrl.$name, false);
      if (scope.invalidCallback) scope.invalidCallback({
        message: messageToShow
      });
      if ($validationProvider.invalidCallback) $validationProvider.invalidCallback(element);

      return false;
    };
```
Why do you try to get message to show before checking whether provider configured to show error messages or not? Why do you pass this message to invalidCallback?

I've modified this code and made it work as previously and I can make PR.

Please, let me know.

Thanks

**Comment by huei90** [comment]
Hi @pyalxx 

Thanks for your question.

You are right, we don't really need to define `messageToShow` if doesn't want to show it.

Using `$validationProvider.showErrorMessage = false` only disable display error message, 
doesn't remove the invalidCallback.
