### ISSUE TITLE
how to validate with condition

### ISSUE THREAD

**Issue by wikimo** [huei90/angular-validation#152]
if condition true validate. can it to be config, thanks

**Comment by huei90** [comment]
you can put your condition in `ng-click`, then execute `angular validation submit`

**Comment by wikimo** [comment]
but if no ng-click, where to put the  condition, the validateion submit method ?

**Comment by huei90** [comment]
Hi @wikimo 
within `ng-click`, you can manually trigger validate.
you can see this as example.
https://github.com/huei90/angular-validation/blob/master/demo/demo.js#L112

`validation-submit` is just a directive `angular-validation` provide, it will execute `$validationProvider.validate(form)`, you can find it here
https://github.com/huei90/angular-validation/blob/master/src/submit.directive.js#L20

**Comment by wikimo** [comment]
Hi, @huei90 

Maybe your suggestion isn't i needed.

``` html
<input type="text" name="age" ng-model="age" validator="required"  validator-condition="!username">
```

want to a directive 'validator-conditon' like that, if username isn't blank, the required need work. if blank,  not work.


The method you provide ,is it means  remove the condition to validation submit.

thanks.

**Comment by huei90** [comment]
Have you tried write the directive `validator-condition` ?

**Comment by wikimo** [comment]
No, wanted function like this, only implement myself. The framework do not
provide?
Huei Tan <notifications@github.com>于2015年11月5日 周四10:29写道：

**Comment by huei90** [comment]
Yes, currently angular-validation doesn't have the directive in condition. 

@lvarayut  What do you see for this feature? I would like to implement `validation-condition`
It will works perfectly with only in `validation-submit`. (not including in manual validate and reset)

**Comment by wikimo** [comment]
OK, thanks for your help. @huei90

**Comment by lvarayut** [comment]
Is it the same as writing a rule?  You could set the `ng-model` as object, then write a new rule to verify it.

**Comment by wikimo** [comment]
The current ng-model may relate to another to verify, can rule pass paramters. @lvarayut

**Comment by lvarayut** [comment]
I just got your point! In that case, we need `validator-condition`, or any clear name, as you suggested. It couldn't be hard to implement it. PR's really welcomed.

**Comment by huei90** [comment]
Hi @wikimo 

First of all, thanks for raising this issue and giving us the opportunity to think about.

As I said before, we can handle this condition check within the `ng-click` as below

```html
<form name="Form">
    <label>Required</label>
    <input type="text" name="required" ng-model="form.required" validator="required">
    <button ng-click="submit(Form)">Submit</button>
</form>
<script>
// ...
$scope.submit = function (form) {
    // condition check
    if (/*some condition*/) {
        $validatorProvider.validate(form);
    }
}
// ...
</script>
```

This works perfectly in your case by checking the condition.

And you suggest a feature using a new directive named `validation-condition`, so it will become

```html
<form name="Form">
    <label>Required</label>
    <input type="text" name="required" ng-model="form.required" validator="required">
    <button validation-submit="Form" validation-condition="some_condition" ng-click="next()">Submit</button>
</form>
```

It breaks the rule in `angular-validation`

> Client-side Validation should be simple and clean. 

adding `validation-condition` will make us get confused - what about condition check for reset? how about adding `validation-reset-condition` and `validation-submit-condition`, this is not the one I want for the validation library. 

I suppose that your case is rare and in my experience, by using the condition,
we will use `ng-disabled` to disable the submit button instead of checking in core function.

Hope this is fine.

What do you see @lvarayut

**Comment by wikimo** [comment]
@huei90  thanks for your help. i've got what you said.

> adding validation-condition will make us get confused - what about condition check for reset? how  about adding validation-reset-condition and validation-submit-condition, this is not the one I want for the validation library.

i think the suggestion what @lvarayut  said, may write a rule can solve it, like the rule minlength /  maxlength. give the paramters to the rule can do it.

**Comment by huei90** [comment]
:+1: Thanks for giving us a thought of this. :smile:

**Comment by wikimo** [comment]
the last question, how can i get the $scope in rule method, want the rule get the var in $scope, that i can deal with the condition. @huei90

**Comment by huei90** [comment]
Hi @wikimo I don't suggest you to use `$scope` in rule,

because the rule is for global used, and if you use $scope, that's mean you need to define them before using.

Therefore, using a `attrs` to do the condition check is enough for global.

**Comment by lvarayut** [comment]
>adding validation-condition will make us get confused - what about condition check for reset? how about adding validation-reset-condition and validation-submit-condition, this is not the one I want for the validation library.

@huei90 Sorry for late reply. I totally agree with your solution. That's what I was thinking at the first time and suggested to write a rule instead of creating the new directive.

**Comment by huei90** [comment]
Thanks @lvarayut :beers:

**Comment by bossbyte** [comment]
Check this rule:

`
                                /**
                                 * use example
                                 * validator="conditionRequired" validator-condition-form="clientForm" validator-condition="or" validator-condition-fields='["sname","email"]'
                                 * 
                                 */
                                conditionRequired: {
                                        
                                    exp: function (value, scope, element, attrs) {
                                        
                                        /**
                                         * Zwraca true jesli element ma wartosc
                                         */
                                        function _checkValue(val){
                                            
                                            if (_.isUndefined(val)){
                                                return false;
                                            }
                                            
                                            if (_.isNull(val)){
                                                 
                                                 return false;
                                            }
                                            
                                            if (_.isEmpty(val)){
                                                 
                                                 //elment pusty np pusty string
                                                 return false;
                                            }
                                            
                                            //element ma wartosc
                                            return true;
                                        }
                                        
                                        if (_.isUndefined(attrs.validatorConditionForm) ||  _.isUndefined(attrs.validatorCondition) || _.isUndefined(attrs.validatorConditionFields)){
                                            
                                            throw "No validator-condition and validator-condition-form, validator-condition-fields atrributes.";
                                        }
                                        
                                        var form=scope[attrs.validatorConditionForm];
                                        
                                        var fields=JSON.parse(attrs.validatorConditionFields);
                                        
                                        var results=[];
                                        //tablica czy wymagane pola maja wartosci
                                        for (var field in fields){
                                            
                                            
                                            results.push(_checkValue(form[fields[field]].$$rawModelValue));
                                            
                                             
                                            
                                        }
                                        
                                        //tablica results w niej booleany
                                        // jesli true element jest wypelniony
                                        // jesli false pusty
                                        
                                      
                                        //czyli wystaczy ze jeden z nich ma true i juz walidujemy
                                        if (attrs.validatorCondition=='or'){
                                            
                                            var result=false;
                                            for (var k in results){
                                            
                                            result=result || results[k];

                                            
                                            }
                                            
                                        }
                                        
                                         //czyli wszystkie musza miec true i walidujemy
                                        if (attrs.validatorCondition=='and'){
                                            
                                            var result=true;
                                            for (var k in results){
                                            
                                            result=result && results[k];

                                            
                                            }
                                            
                                        }
                                        
                                        
                                        if (result){
                                            //pola wypelnione walidujemy
                                            return _checkValue(value);
                                        }else
                                            return true; //nie walidujemy bo pola nie sa wypelnione
                                        
                                        
                                       
                                    },
                                    msg: _l('value is required')

                                }`
