### ISSUE TITLE
v1.3.2升级到v1.3.3出现不兼容的情况

### ISSUE THREAD

**Issue by mingjunyang** [huei90/angular-validation#153]
原有的表单验证功能是在v1.3.2下写的，bower自动升级到v1.3.3之后出现问题。

``` html
<input class="form-control" message-id="message-fare" name="fare" ng-model="form.fare" number-error-message="请填写正确的金额格式" placeholder="请输入金额" ng-blur="sumFare()" type="text" valid-method="blur" validator="required,money">
```
当输入错误之后，再输入正确的值，会出现提示验证提示信息不消失的情况。

**Comment by huei90** [comment]
> 会出现提示验证提示信息不消失的情况

請問這裏的 提示驗證提示訊息 是指錯誤還是成功訊息呢？

另外，`number-error-message` 沒有找到對應的 number 驗證。

可否提供多一些資料呢？因為我看這個 html 是沒有問題的。

**Comment by mingjunyang** [comment]
晚上我去弄一个在线演示出来。

**Comment by huei90** [comment]
好 麻煩你了。

**Comment by mingjunyang** [comment]
地址在这里 https://github.com/mingjunyang/angular-validation-demo.git  我猜测出现这个问题的原因应该是我使用了自己的 validation.rule

**Comment by huei90** [comment]
感謝回報

上次修復的問題造成了這個 bug
https://github.com/huei90/angular-validation/commit/e53469c08a7e6e4ef7c8a60c0e67683bd7dd68ad

不是你 demo 的問題，這是一個 bug。

你先暫時使用 1.3.2 舊的版本，修復後我就會推到 1.3.4 ，屆時再通知你。

謝謝你！

**Comment by huei90** [comment]
`no-validation-message` conflict with 
`$validationProvider.showErrorMessage`
`validationProvider.showSuccessMessage`

**Comment by huei90** [comment]
@mingjunyang Fix on last commit.
Please try again.

**Comment by mingjunyang** [comment]
@huei90 try  it weekend

**Comment by huei90** [comment]
Thanks @mingjunyang
