### ISSUE TITLE
Include icon for input

### ISSUE THREAD

**Issue by Jeevanandanj** [huei90/angular-validation#156]
Can we include tick icon (or any other icon) if user give proper information on input?

**Comment by huei90** [comment]
Refer to here.
https://github.com/huei90/angular-validation/blob/master/API.md#custom-the-validinvalid-message-style-html-in-config-

**Comment by Jeevanandanj** [comment]
Sorry for not to read api doc properly. Thanks for the nice plugin between top most 5.

I had another issue is that, When I click the plugin is showing the proper error message. I've hidden the success message.

But after hide the success message, error message is still showing for the proper input.

Do I missed anything to configure?

**Comment by huei90** [comment]
This is same problem as
https://github.com/huei90/angular-validation/issues/153

I will try to fix it later, but I still need some time to define those features.

**Comment by huei90** [comment]
What do you mean **highlight** the input.

**Comment by huei90** [comment]
If you are using **bootstrap**

refer to here for the highlight input.
https://github.com/huei90/angular-validation#integrating-with-twitter-bootstrap

**Comment by Jeevanandanj** [comment]
Thanks.
