### ISSUE TITLE
Remove success message

### ISSUE THREAD

**Issue by Jeevanandanj** [huei90/angular-validation#157]
Error message is showing even after proper input (after hide success message.)

**Comment by huei90** [comment]
same problem of my reply here
https://github.com/huei90/angular-validation/issues/156

**Comment by Jeevanandanj** [comment]
Finally I did workaround for this. I've added empty span to the success message like following.

required-success-message="&lt;span&gt;&lt;&#47;span&gt;".

This is working.

**Comment by huei90** [comment]
Ok, good to see this works. But I should fix the bug.
