### ISSUE TITLE
Validate one control at a time

### ISSUE THREAD

**Issue by Jeevanandanj** [huei90/angular-validation#158]
I want to validate one control at a time. After giving proper input, the validation should go to next. Can we do this one?

**Comment by huei90** [comment]
yes, you can validate one, or multiple using array, and even whole form.

```html
<form name="Form">
    <div class="row">
        <div>
            <label>Required</label>
            <input type="text" name="required" ng-model="form.required" validator="required">
        </div>
        <div>
            <label>Url</label>
            <input type="text" name="url" ng-model="form.url" validator="required, url">
        </div>
        <button ng-click="submit(Form)">Submit</button>
    </div>
</form>

<script>
// .. some code
$scope.submit = function (form) {
    // validate first "required" input
    $validationProvider.validate(form.required);
}
</script>
```

**Comment by Jeevanandanj** [comment]
Oh great. superb. How do I use call back which we use in html attribute?

**Comment by huei90** [comment]
Do you mean `validation-submit` ?

you can try

```html
<button validation-submit="Form.required" ng-click="next()">Submit</button>
```

**Comment by Jeevanandanj** [comment]
No I am asking about invalid-callback.

**Comment by Jeevanandanj** [comment]
I can't inject $validationProvider in controller. I am getting issue :-(

**Comment by huei90** [comment]
You can assign your callback for specified input element.
https://github.com/huei90/angular-validation/blob/master/API.md#add-valid-callback-function-invalid-callback--valid-callback

**Comment by huei90** [comment]
No, you can use it, Try more =)

**Comment by Jeevanandanj** [comment]
Error: [$injector:unpr] Unknown provider: $validationProviderProvider <- $validationProvider <- signUpController

I am getting this error.

**Comment by huei90** [comment]
you can find the demo code here.
https://github.com/huei90/angular-validation/blob/master/demo/demo.js#L93

**Comment by Jeevanandanj** [comment]
signUpModule.registerController('signUpController', ['$scope','$validationProvider',function ($scope, $validationProvider) {
}]);

I have tried like above and got the issue. Am I doing in the correct way?

**Comment by huei90** [comment]
No.

signUpModule.registerController('signUpController', ['$scope','$validationProvider',function ($scope, $validation) {
}]);

remove the provider.

**Comment by Jeevanandanj** [comment]
Thanks. I can get the validation provider using var $validationProvider = $injector.get('$validation');

But after that I did like $validationProvider.validate(form.CompanyName).success(function (data) {
}).error(function (data) { });

In error I can show the error message for company name itself. If I have 10 inputs, then I need to do 10 if conditions to check.

Is there any shortcuts with one or two line?

I may miss any logic. Can you guide me?

**Comment by huei90** [comment]
no.

you are validating one by one, so there is no shortcut. unless you validate all in once.

**Comment by Jeevanandanj** [comment]
can you made any new feature to set one by one validation in html itself like success message on or off? there is one by one validation in angular itself. User may leave because of this. Can you please do it for us?

**Comment by huei90** [comment]
@Jeevanandanj Can you show me how do you do one by one using angular  itself?
