### ISSUE TITLE
Add index.js or main to package.json so require('angular-validation') will work properly

### ISSUE THREAD

**Issue by eenewbsauce** [huei90/angular-validation#163]

**Comment by huei90** [comment]
@eenewbsauce Do you mean adding this?

https://github.com/npm/npm/blob/master/package.json#L30

**Comment by SamiTriki** [comment]
I think that's what he means, and +1

**Comment by huei90** [comment]
But I'm not sure which case

we will use

```
require('angular-validation')
```

but I can do that, no bad effect to the repo.

**Comment by SamiTriki** [comment]
Personally, I use browserify on my client app so I just require it this way, I currently have to use it this way
```
require('angular-validation/dist/angular-validation')
``` 
I think having the right file in the main is more intuitive for people using npm, thanks !

**Comment by huei90** [comment]
DONE @SamiTriki See if this works for you

**Comment by SamiTriki** [comment]
Perfect, and thanks for the library

**Comment by huei90** [comment]
You're welcome
