### ISSUE TITLE
Remove Grunt support, change to npm run.

### ISSUE THREAD

**Issue by huei90** [huei90/angular-validation#169]
What do you see. @Nazanin1369 @lvarayut

**Comment by Nazanin1369** [comment]
Totally agree. I can go ahead and change that...

**Comment by huei90** [comment]
Thank you @Nazanin1369 We can have the discussions here.

**Comment by lvarayut** [comment]
@huei90, if we deleted it, would it be still possible to do `liverealod`, `concat`, 'combine`, `test`, and etc?

**Comment by huei90** [comment]
@lvarayut I have never tried this before, but npm is possible to do the tasks.

read

http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

**Comment by lvarayut** [comment]
The only disadvantage is that we can't put any comments inside JSON file; `package.json`. If the project was getting bigger, it would be more difficult to manage the file.

**Comment by huei90** [comment]
> we can't put any comments inside JSON file;

yes, this is the cons, using grunt or gulp are the easier tools to use.

using npm will looks like this

```
"scripts": {
    "build": "ecmarkup --js=spec.js --css=spec.css spec.emu | js-beautify -f - --type=html -t > index.html",
}
```

**Comment by Nazanin1369** [comment]
I think one thing to consider is the flexibility of the tasks which I think using "Gulp" is the best.
Gulp pipes makes writing the tasks more readable and easier.

I am not agree with Grunt at all.

What do u think about Gulp?

https://ponyfoo.com/articles/choose-grunt-gulp-or-npm

**Comment by lvarayut** [comment]
I prefer gulp more than other. It's much faster than grunt and more
flexible than package.json.

**Comment by Nazanin1369** [comment]
Yes! Agree, then let's move toward gulp is Huei agree too.

**Comment by huei90** [comment]
`grunt` or `gulp` look same to me, we are not a big project so the speed is not the matter.

In this topic, I am considering about `npm` for the management, less code in the project.

now, Ii see the benefit from `npm run`

> we don't really need both grunt and gulp because npm can do the exactly same task. Dealing with the cons, we can write more on the CONTRIBUTING.md

OR, we can continue to focus on the feature development. we have a great improvement recently, thanks to @Nazanin1369 isolate scope feature, @lvarayut validation-group feature, these are the good processes and results from the team.

Let's leave the issue here, maybe we can have more discussions here.

@kcliu - what do you see.
https://github.com/huei90/angular-validation/issues/107

**Comment by Nazanin1369** [comment]
I think this is a low priority enhancement. We can make it unless there is
no reported issue or higher priority enhancement ticket available.

**Comment by huei90** [comment]
I have added this as the low priority.
https://github.com/huei90/angular-validation/issues/137#issuecomment-149781699

Let me close it first, open it when the day we start doing this.
