### ISSUE TITLE
Migration to Typescript

### ISSUE THREAD

**Issue by lucax88x** [huei90/angular-validation#170]
please add enhancement label

**Comment by huei90** [comment]
Hi @lucax88x Thanks for your enhancement suggestions.

We have a board that in our list.
https://github.com/huei90/angular-validation/issues/137

I'm prefer ES6 rather than TypeScript.

**Comment by Nazanin1369** [comment]
I agree with ES6 more also specifically for this project.

**Comment by lucax88x** [comment]
why ES6 instead of Typescript?

while writing tests or enhancement on library I was so terribly missing the intellisense of Karma & Angular.

Once you're in Typescript, you won't get out easily, and Google it's taking this as standard.

Typescript would also keep backwards compatbility, where ES6 would fail.

**Comment by huei90** [comment]
I'm not interested in developing angular-validation in any compiler style of JavaScript but contributions are **definitely welcome**.

This is the library for angular, unless angular is seriously focus on compiler style JavaScript (angular2 is not in our scope right now), I will choose to do it in pure javascript and enhance the feature of angular-validation.

I love to accept angular-validation in any style of code, CoffeeScript, LiveScript, TypeScript, Babel ...
It will be perfect to fork as _angular-validation-coffee_, _angular-validation-live_, _angular-validation-type_ (just as the example).

Hope this is clear :sunny:

**Comment by Nazanin1369** [comment]
Agree with @huei90

**Comment by huei90** [comment]
list in **Ticket and Enhancement #174**
