### ISSUE TITLE
Angular i18n support

### ISSUE THREAD

**Issue by Nazanin1369** [huei90/angular-validation#176]

**Comment by huei90** [comment]
Cool, this perfectly integrating angular-translate to our project.
Since this effect demo page only, do you want to move `resource` folder to `demo`?

**Comment by Nazanin1369** [comment]
Sure I will do that.

**Comment by Nazanin1369** [comment]
@huei90 Need some help with Chinese language. Need someone to fill the json file later on

**Comment by Nazanin1369** [comment]
@huei90 Done with i18n. Please double check the Chinese translations

**Comment by huei90** [comment]
Oh! I think I miss understand your commit.

Your change is for the demo page, i thought it was translation for the angular-validation output message

But anyway, we can provide more language to the user.

**Comment by huei90** [comment]
Close the issue now.
