### ISSUE TITLE
Add features to custom Message Element

### ISSUE THREAD

**Issue by hungdoan2** [huei90/angular-validation#182]
**STORY**
I have requirement like this(not place msg element after input):
````html
<div>
	<label>
		<input type="text" name="fullName" validator="required" />
	</label>
	<!-- I WANT MY MESSAGE ELEMENT HERE INSTEAD AFTER input -->
</div>
````
**Existence solution**: Use `message-id`
`But` : I don't want to define Msg Element by myself . I want it automatically.

**New solution**
Define 2 news function: 
`$validationProvider.addMsgElement`  : Response for adding Msg Element 
and 
`$validationProvider.getMsgElement` : Respone for getting Msg Element

Here is my implement: https://github.com/hungdoan2/angular-validation/commit/683f7cfdbeac83a1e43eef1559f4b9a24111ffe1

**Comment by huei90** [comment]
This is cool @hungdoan2 Without this we need to apply a lot of `message-id`, since we can have the global settings for the format.

Thanks @hungdoan2 I will merge your commit :smile:

**Comment by lvarayut** [comment]
Love the idea :)

**Comment by huei90** [comment]
@lvarayut Me too, using a lot of `message-id` is kind of tragedy.

**Comment by huei90** [comment]
Update on here.
https://github.com/huei90/angular-validation/pull/183
