### ISSUE TITLE
Radio Group加上validator="required"后只会对最后一个Radio生效，这个怎么fix啊？

### ISSUE THREAD

**Issue by knonginda** [huei90/angular-validation#186]
以下是我的测试代码，确实只有test2的radio会校验，我看了你的demo，只有一个radio button的example，所以我不知道是不是它不支持多个radio button。

    <div class="form-group">
        <input validator="required" type="radio" ng-model="test" name="test" value="Y" id="test1">
        <label for="test1">Test One</label>
    </div>
    <div class="form-group">
        <input validator="required" type="radio" ng-model="test" name="test" value="N" id="test2">
        <label for="test2">Test Two</label>
    </div>

**Comment by huei90** [comment]
Try using `validation-group`
https://github.com/huei90/angular-validation/blob/master/Q%26A.md#can-i-validate-multiple-checkbox

**Comment by knonginda** [comment]
validation-group 我试过了，它好像只支持不同model和不同name的，但是我的radio必须是同一个model。

**Comment by huei90** [comment]
这里所有的验证都支持不同model不同name。

在你这个范例中，ng-model都使用同一個，所以兩個input都會是同樣的值

请问你是在什么情况下需要这样的表格？

**Comment by knonginda** [comment]
我遇到这样一种情况，就是如果我提交form，那么以下两个radio只有最后一个radio会触发ng-invalid，而不是所有的radio都触发ng-invaild，因为我需要这个class来渲染radio的样式不，知道可以不可以。
<div class="form-group">
    <input validator="required" type="radio" ng-model="test" name="test" value="Y" id="test1" class="ng-pristine ng-untouched ng-pending">
    <label for="test1">Test One</label>
</div>
<div class="form-group">
    <input validator="required" type="radio" ng-model="test" name="test" value="N" id="test2" ng-pristine ng-untouched ng-invalid ng-invalid-test>
    <label for="test2">Test Two</label>
</div>

**Comment by huei90** [comment]
那么我建议你拆成两个 model
然后让其中一个 model watch 另一个 model 改变他的值
这样就能达到你的目的

angular-validation 是针对提供的 model name 来做验证，在你的情况下只好稍微做个变形。

**Comment by knonginda** [comment]
好的，非常感谢！！！

**Comment by huei90** [comment]
:beers:

**Comment by pronebel** [comment]
radio 同一个组很常见啊

<input validator="required" type="radio" ng-model="test" name="test" value="Y" id="test1" class="ng-pristine ng-untouched ng-pending">
<label for="test1">Test One</label>

<input validator="required" type="radio" ng-model="test" name="test" value="N" id="test2" class="ng-pristine ng-untouched ng-invalid ng-invalid-test">
<label for="test2">Test Two</label>


这个而且是angular自带的方式，如果要给ng-model设置不同的，那有5-6radio组，那且不是疯了啊

这个控件 有更好的支持方式么
