### ISSUE TITLE
Why default validity is false?

### ISSUE THREAD

**Issue by zack9433** [huei90/angular-validation#19]
I think don't set validity to false when initial.

If i set a valid value to input as default value when initialize form and this input valid-method="blur", but i get this form $valid is false.

**Comment by zafarullahjoiya** [comment]
i am facing a strange problem.i am really tired to configure this problem.i see the default value of $valid is false when user fill the form correctly it become true then submit button enable.can any one tell me here how we can set the default value of $valid false instead of true ?

**Comment by huei90** [comment]
Hi @zafarullahjoiya Sorry that I didn't mentioned this on the Document.

Here's you can change the Initial value of $valid
https://github.com/huei90/angular-validation/blob/master/API.md#customizable-initial-validation

**Comment by zafarullahjoiya** [comment]
HI Huei Tan

Thanks for response....i have resolve the issue...The issue was with
ng-model.
Thanks once again

zafarullahjoiya

On Thu, May 7, 2015 at 6:34 PM, Huei Tan <notifications@github.com> wrote:

> Hi @zafarullahjoiya <https://github.com/zafarullahjoiya> Sorry that I
> didn't mentioned this on the Document.
>
> Here's you can change the Initial value of $valid
>
> https://github.com/huei90/angular-validation/blob/master/API.md#customizable-initial-validation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/huei90/angular-validation/issues/19#issuecomment-100064544>
> .
>



-- 
Web Developer
