### ISSUE TITLE
valid-method="submit" acts like a watch after submit

### ISSUE THREAD

**Issue by j-langlois** [huei90/angular-validation#192]
It seems the attribute valid-method="submit" turns to a watch after a form has been validated. The valid and invalid callbacks will be called on every input change. This behavior is great when the validation fails, since it helps the user in his entry of a proper input, in opposition to valid-method="submit-only". However, when the validation succeeds, is it possible to get back to the initial state where it needs a submit to validate the inputs all at once, instead of having them behave like a watch ?
Thanks!
Joel

**Comment by huei90** [comment]
doesn't `submit-only` work to you?

**Comment by j-langlois** [comment]
Thanks for the response. Yes submit-only works for me, but it doesnt have the wonderful behavior of helping the user fix its input upon typing after the validation fails.

Say you have an optional field of VAT number, I noticed the following drawbacks for every method:

using valid-method="submit".
1. VAT number: <no input>
2. User clicks submit
3. The form gets validated successfully since empty is allowed for this field.
4. The user changes adds a VAT number, but until the field fits the regex, the watch-like behaviour after a previous submit will display "invalid VAT number format".

using valid-method="submit-only".
1. VAT number: <input with wrong format>
2. User clicks submit
3. The field gets validated with error since the format is wrong.
4. The user changes his VAT number, but the field keeps the invalid state until another submit is clicked.

What I would suggest as a user-focused recommandation is having a way to disable the watch-like behavior upon a successful submit using valid-method="submit". I think a reset callback that does not clear the values could do it. I know there's another issue about this concern, but that way the following scenario could be implemented:

using valid-method="submit".
1. VAT number: <some input>
2. User clicks submit
(first scenario)
3. The form gets validated successfully since the input is allowed.
4 Catch the success in our controller, and clear the has-success classes for every input. Remove the watch-like behaviour on every input.
(second scenario)
3. The form gets validated with error since empty the input is in the wrong format.
4. Keep the watch-like behaviour to help the user fix its input until the submit button is clicked again with a valid form.

Thanks for the great work BTW. I have a huge validation rule file for a ton of very popular formats, I will try to submit a pull request ASAP :)

Joel

**Comment by huei90** [comment]
For the first scenario, I would suggest using success callback to clear the classes, this is not the submit or submit-only usage purpose

Second, using submit type is fine.
