### ISSUE TITLE
Not required fields treated as required

### ISSUE THREAD

**Issue by rc125** [huei90/angular-validation#193]
I have two fields, one is required and the other not, but when I submit the two are treated as required

Example: https://plnkr.co/edit/mNBrXBvKwmdHvzuJZ6ZD?p=preview

**Comment by Nazanin1369** [comment]
Your Plunker does not have anything in the body rathe than: 
 "<body ng-controller="MainCtrl">
    <h1>Hello Plunker!</h1>
</body>"

**Comment by Nazanin1369** [comment]
This is because the regex for Url does not accept empty string . You can edit your validation rule regex to accept empty string too

**Comment by huei90** [comment]
Open if any other issues.
