### ISSUE TITLE
Enhancement for validators

### ISSUE THREAD

**Issue by rickerd** [huei90/angular-validation#194]
Validation contribution:

- [ ] Alphabetical validator
- [ ] No special characters

**Comment by lvarayut** [comment]
You could also write your own validators. Take a look at [Setup a new Validation in API.md](https://github.com/huei90/angular-validation/blob/master/API.md#setup-a-new-validation-setexpression-setdefaultmsg-with-regexp-or-function-in-config-phase).

**Comment by rickerd** [comment]
I know, i'm working on these validators now.
But the second question if a file or something could be extended was my insecure question.

**Comment by lvarayut** [comment]
I'm not quite sure what you meant. Can you provide some example?

**Comment by rickerd** [comment]
Im sorry, i dind't read the validation API completely.
My "question" is more a roadmap now what i;'m going to contribute.

The code is super clean, really nice coded.

**Comment by lvarayut** [comment]
Perfect. We're look forward to merging your PRs. :smile: . Is it safe to close this issue right now?

**Comment by huei90** [comment]
The rule is just the showcase/example, not recommended for the real case use.

**Comment by huei90** [comment]
Closed.
