### ISSUE TITLE
Valid message disabled by default

### ISSUE THREAD

**Issue by rickerd** [huei90/angular-validation#195]
I want to know if people agree with me if the valid message should be disabled by default and if you want to show it you have to set it like you do now if you want to disable it.

I don't want to put it to all my elements that i don't want to valid validate because i never want to show a valid message.

**Comment by rickerd** [comment]
Found it in the documentation.

`.config(['$validationProvider', function ($validationProvider) {
    $validationProvider.showSuccessMessage = false; // or true(default)
    $validationProvider.showErrorMessage = true;
}])`

**Comment by huei90** [comment]
YES :smile:
