### ISSUE TITLE
Float Number generate error with use of number validation 

### ISSUE THREAD

**Issue by sachinlogiciel** [huei90/angular-validation#196]
I want to apply an number validation on input field but value can be float or double but when we enter float number it generate an validation error. Any idea how to solve this?

**Comment by huei90** [comment]
> Generating a validation error 

It depends on the validation rule you given. Please try to customize your rule to adopt float input.

**Comment by sachinlogiciel** [comment]
Thanks

**Comment by huei90** [comment]
yw
