### ISSUE TITLE
show multiple validation rule error messages

### ISSUE THREAD

**Issue by daituzhang** [huei90/angular-validation#199]
Hi,
Thank you for the awesome library!
I'm setting up multiple validation rules for password:
ex:
Lowercase character
Uppercase character
Digit
Symbol

and I have wrote custom regex and defaultMsg for each rule.
What I am expecting is that all rule error messages will be shown up if not met,
and if the rule is fulfilled, that rule error message will disappear.
However right now, there's only one error message at a time.

Is there way that I can show multiple error messages? Thank you!

**Comment by huei90** [comment]
In the process of the validation, if you have more than one validate rule, it will go one by one. In the case, it will stop the validation and show the specific error message when it fail on any rule.

> all rule error messages shown up
You may custom it by yourself or include all the rules into one

> rule is fulfilled
Yes, the error messages will disappear once it has no error

:smile:

**Comment by daituzhang** [comment]
Thank you I made a custom one.
