### ISSUE TITLE
Server-side validation

### ISSUE THREAD

**Issue by jzimmek** [huei90/angular-validation#2]
Most common case and well understood example is the unique email validation during a user registration (JSON-Api).

Can you add an example on how to implement this in angular-validation.

**Comment by RichardSilveira** [comment]
I´ve a lot os issues around async/remote validation, either using your or nelsonnomuto´ validation pluging, i made a simple test with nelsonnomuto version and i could see that works well with native new feature of angular 1.3 about async validations, your pluging work´s too? Have you a sample demo with angular 1.3 async validation?

**Comment by huei90** [comment]
@RichardSilveira Hi, in the currently angular-validation version, the answer is no. (not yet)

Do you mind help me on testing async for angular-validation?

**Comment by RichardSilveira** [comment]
Ok, i will try do it and will give to you a feedback and plunkr demo, i think that it´s works...

**Comment by huei90** [comment]
Thanks!!!
