### ISSUE TITLE
Remove validation for specific fields on the fly

### ISSUE THREAD

**Issue by joseluisq** [huei90/angular-validation#200]
How can I remove validations for specific fields on the fly and vice versa?

**Comment by huei90** [comment]
@joseluisq Do you mean changing or deleting the validator ?

**Comment by joseluisq** [comment]
> @joseluisq Do you mean changing or deleting the validator ?

Yes, changing and deleting validation.

**Comment by huei90** [comment]
recompile the form may works. but I haven't tried it yet. 
Do you mind trying on `$compile` the form?

**Comment by joseluisq** [comment]
> recompile the form may works. but I haven't tried it yet. 
> Do you mind trying on $compile the form?

No, I didn't tried it..
But It would be great! support for changing or deleting validation for specific fields 😄

**Comment by huei90** [comment]
It's difficult though it need to re-generate all the validation.

changing/deleting means have to **watch** the validation, I may suggest we use a method API to manually trigger the compilation.

what do you see?

**Comment by joseluisq** [comment]
Fine, for now I will try to trigger the compilation.
Thanks 👍
