### ISSUE TITLE
Set value zero generate invalid error on form load

### ISSUE THREAD

**Issue by sachinlogiciel** [huei90/angular-validation#201]
I set a validation on some field of form and on form load i set value 0 on that and it generate validation error on form but i set validation that allow zero so if i remove prefilled zero then again fill zero value form become valid but when i set value 1 on form load i valid on load. I don't understand why it is like that so moreover when value set 0 on form load it doen't let me submit a form not even show any validation error because rules allow 0 to be filled but when i debugged form a validation set on field untill i remove prefilled 0 set a 0 again so is this a angular problem or this plugin set validation on 0 on form load. if this please let me know any solutions on that so form is valid on load even if value is set to zero.

**Comment by huei90** [comment]
Do you mind giving the step by 1,2,3.. I'm not sure if I understand the meaning.
