### ISSUE TITLE
Validation problem when try to put a part of value of the mask

### ISSUE THREAD

**Issue by eduardonaguiar** [huei90/angular-validation#207]
In my case I use ui-mask and need to put a parcial string in a input masked so even with allowInvalidValue setted to true the model doesn't validate neither show the validation message. If I put a complete value the model it is validated.

**Comment by Nazanin1369** [comment]
Can u put up an example

On Friday, May 20, 2016, eduardonaguiar <notifications@github.com> wrote:

> In my case I need to put a parcial string in a input masked so even with
> allowInvalidValue setted to true the model doesn't validate neither show
> the validation message. If I put a complete value the model it is validated.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/huei90/angular-validation/issues/207>
>


-- 
Best Regards,

**Comment by eduardonaguiar** [comment]
<input 
      id="phone" 
      name="phone" 
      type="text" 
      class="form-control input-md" 
      ng-model="data.phone" 
      ui-mask="(999) 9999-9999" 
      validator="required" 
      valid-method="submit" 
      allow-invalid-value
  >

If I type (000) 0000-000_ (no complete the mask) and try to validate ( $validation.validate(form) ), the method doens't execute sucess promise and doens't show the required message from input. When I console the form object the input appear in $error section as a invalid input.

**Comment by Nazanin1369** [comment]
You are validating whether the value is required, SO when you enter a half of the mask there is no validation. 
Also you have allow-invalid-value directive which I am not sure why it is there. Can you try this without this directive

**Comment by eduardonaguiar** [comment]
I'm working on a new GUI for a old database, so the values for this data can be broken for this new mask. 
If the user try to alter the form with the broken data field the form is not validating. I just need that the form be validate with the broken masked data.

**Comment by huei90** [comment]
you need to customize your validator "required"
