### ISSUE TITLE
Validator for confirm password ?

### ISSUE THREAD

**Issue by maxhan247** [huei90/angular-validation#211]
For issue in https://github.com/huei90/angular-validation/issues/24

```html
<input type="password" ng-model="password"  validator="..."/>
<input type="password" ng-model="passwordAgain" validator="matching" validator-password="{{ password }}"/>
```

```js
.setExpression({
    matching: function (value, scope, element, attrs) {
        return value === attrs.validatorPassword;
    }
})
```

if we enter password first. then I enter passwordAgain first and then I change password, it should show "not match", but it not.

Because the matching in here doesn't watch the change of ` ng-model="password"`. It only works when I change ng-model="passwordAgain".

Would like to make an example, the functionality as same as [plunkr](http://plnkr.co/edit/FipgiTUaaymm5Mk6HIfn) ?

In my code, I use:
```html
<input type="password" ng-model="vm.password"  validator="..."/>
<input type="password" ng-model="vm.passwordAgain" validator="matching" validator-password="{{ vm.password }}"/>
```

The controller as syntax will bring this problem ?
![password1](https://cloud.githubusercontent.com/assets/19585802/15583573/3ed9d770-232b-11e6-86e1-969d192ea9e9.PNG)
![password2](https://cloud.githubusercontent.com/assets/19585802/15583575/41055a10-232b-11e6-8717-59b32e45103c.PNG)
![password3](https://cloud.githubusercontent.com/assets/19585802/15583609/6a8c1180-232b-11e6-9ba6-a7a0831aea9a.PNG)

**Comment by maxhan247** [comment]
I already slove in https://github.com/huei90/angular-validation/issues/24

**Comment by huei90** [comment]
hmmm... i'm not really understand it. What's the version of
angular-validation are you using now?

**Comment by maxhan247** [comment]
Is angular-validation 1.4.1

**Comment by maxhan247** [comment]
This is my code: [](https://plnkr.co/edit/47RzIK)

**Comment by huei90** [comment]
I understand your question after formatting the markdown language.

You are asking for the first input change observe the second input validation, currently there is no built-in function to do that, but you can manually trigger the `$validationProvider.validate(<specific form>)` when the input is changed.
