### ISSUE TITLE
Update dependencies and test it!

### ISSUE THREAD

**Issue by huei90** [huei90/angular-validation#212]

**Comment by huei90** [comment]
nobody 🙇

**Comment by Nazanin1369** [comment]
I will do this

**Comment by huei90** [comment]
ping @Nazanin1369

**Comment by Nazanin1369** [comment]
Will pit up a commit by tomorrow

On Tuesday, July 5, 2016, Huei Tan <notifications@github.com> wrote:

> ping @Nazanin1369 <https://github.com/Nazanin1369>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/huei90/angular-validation/issues/212#issuecomment-230530029>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGFV2InDpkhBnvEY6OgeKFamTHqFZi6pks5qSoZigaJpZM4Ioihe>
> .
>


-- 
Best Regards,

**Comment by huei90** [comment]
I will do it if you are busy on something else. @Nazanin1369
