### ISSUE TITLE
Validation problem when using ngForm.

### ISSUE THREAD

**Issue by eduardonaguiar** [huei90/angular-validation#213]
When I nested some forms, the main validation expect the fill of elements within the sub forms. How do I make nested validations?

**Comment by huei90** [comment]
Do you mean ng-form inside another my-form?

Am Freitag, 3. Juni 2016 schrieb eduardonaguiar :

**Comment by eduardonaguiar** [comment]
Fallow the code:

```
<form id="form">
    <input type="text" name="text1" id="text1" ng-model="data.text1" validator="required" valid-method="submit" />
    <div ng-form="subform1">
        <input type="text" name="text2" id="text2" validator="required" valid-method="submit" />
        <input type="button" name="button1" id="button1" value="add to list1" ng-model="text2" ng-click="add(subform1)" />
        <table>
            <tr ng-repeat="item1 in data.list1" >
                <td>{{item.text2}}</td>
            </tr>
        </table>
    </div>
    <input type="button" name="button1" id="button1" value="Save" ng-click="save(form)" />
</form>
```

In the controller:

```
     $scope.save = function (frm) {
        $validation.validate(frm).success(function () {
          ...
        });
    }

    $scope.add = function (frm) {
        $validation.validate(frm).success(function () {
             $scope.data.list1.push($scope.text2);
             $validation.reset(frm);
        });
    }
```

I fill the list1 in the sub form subform1. When a try save the main form, the model not is validate causa the input text1 is empty. Thats mean the validation in the main form is using all inputs in the form to validate. I just need validate the text1 input. How do I do this approach?

**Comment by huei90** [comment]
Ideally, try to separate the two forms to make your markup clear. 

otherwise you need to manually validate only `text1` that means your code will do a lot of logic.

**Comment by eduardonaguiar** [comment]
The validation doens't work with nested forms?

**Comment by huei90** [comment]
@eduardonaguiar I didn't tried on nested form very deeply, but i would suggest

> try to separate the two forms to make your markup clear.
