### ISSUE TITLE
Problem using built-in validators

### ISSUE THREAD

**Issue by mcblum** [huei90/angular-validation#214]
Any idea what would be causing this error: `vendor.js:31 You are using undefined validator "required"`? My understanding was that required and a handful of others are included. Thanks for your work on this library -- I hope to use it!

**Comment by huei90** [comment]
You need to define the rule in your application, in other words, this error means you didn't define the rule `validator`

**Comment by huei90** [comment]
FYI
https://github.com/huei90/angular-validation/blob/master/src/rule.js

**Comment by mcblum** [comment]
Yep! Thank you. I just missed that step.

**Comment by huei90** [comment]
Great!

Am Mittwoch, 8. Juni 2016 schrieb mcblum :
