### ISSUE TITLE
Question: Triggering a check of a form and showing all errors?

### ISSUE THREAD

**Issue by mcblum** [huei90/angular-validation#216]
Hi. I'm sorry to use the issues panel to submit a question. I've been stuck on this for a couple days. I've tried to copy your exact example from the demo page:

```
function save() {
            $validation.validate('general')
                .success(function() {
                    $ctrl.changeView({view: view});
                })
                .error(function() {
                    NoticeFactory('error', 'Whoops', 'Please check the items in red');
                });
        }
```

The name of the form is 'general'. It always returns an error no matter what I do but the errors (red text next to the input) never appears. Sorry to be a pain in the butt.

Edited to add: I figured out why the form wouldn't validated, it's because I'm an idiot. So that's working now. But when validation fails, how do I show all errors?

**Comment by huei90** [comment]
The general should be the real form scope, try looking for the general in $scope.xxx

**Comment by mcblum** [comment]
Thank you for your response! I just cracked it and it was something really dumb -- in order for the errors to show all input elements must have a name. We typically don't use names since we're doing everything with ng-model, but in this case we needed them. Hopefully this can help someone else if they get tripped up!

**Comment by huei90** [comment]
👍
