### ISSUE TITLE
Validating multiples fields with dependency

### ISSUE THREAD

**Issue by forrochan** [huei90/angular-validation#218]
How do i validate multiple fields with dependency in a form, i mean lets take for example i have a select, which seys "Food, Numbers" and is currently on "Food", next i have a text input called "validationInput" , what i want to do is, if the select is on number, validate that theres is a number on validationInput, and a name otherwise

**Comment by huei90** [comment]
I didn't try it yet, but you can try
https://github.com/huei90/angular-validation#integrating-with-twitter-bootstrap
