### ISSUE TITLE
Give Some example of group validation

### ISSUE THREAD

**Issue by prakashtechmango** [huei90/angular-validation#219]
i have two types of submit buttons one is save and another one is submit. when click save button only few fields only validated . while click on submit button whole form fields should be validated. please give me solution. how to use validation group also?

**Comment by huei90** [comment]
**Submit**

You have to define all `validation` for every single input fields, and $validate all of them. (simple one)

**Save**

You have to define the fields you want to validate on Save with `validation-group`.
Here's the example
https://github.com/huei90/angular-validation/blob/master/API.md#use-a-validation-group-

Hope this is clear.

**Comment by dsvvimal** [comment]
form submit is not working when i use validation group. Could you please help me how to fix this? Below is my code
<form role="form" name="Form"> 
	<input type="email" class="form-control" id="email" placeholder="Email" name="email" ng-model="email" validator="email" valid-method="blur" email-error-message="Invalid Email" style="">
	<input type="password" class="form-control" id="pwd" placeholder="Password" name="password" ng-model="password" validator="required" valid-method="blur" required-error-message="This is required" style="">

	<input type="text" name="email" ng-model="email" validator="required" validation-group="contact"> 
	<input type="text" name="telephone" ng-model="telephone" validator="number" validation-group="contact">
	
	<input type="button" validation-submit="Form" class="btn btn-large btn-block btn_primary" value="Log in" ng-click="login()"/>
	
</form>
