### ISSUE TITLE
checkValid() is failing

### ISSUE THREAD

**Issue by mcblum** [huei90/angular-validation#220]
Hi. We have a multi-part form and we want to validate when the page loads in case some sections are already complete as well as when the user clicks 'save + next'. Validation is working when the user clicks 'save + next' but validation is failing completely when the app loads, even though no data has changed between the load and the button click.

Any idea what might be wrong? Does triggering the form validation via a button click somehow do something different?

**Comment by huei90** [comment]
Is validation able to work even in app loads? loading?

**Comment by mcblum** [comment]
I spent all day trying to figure out what could be wrong and I couldn't do it. The only thing that we were able to find is that on the form $vald and $invald were both undefined. Also, the form is made up of many sub-components so we thought it might be an issue where the form loads but not all of the sub components have loaded so it doesn't actually know if it's valid or not.

**Comment by mcblum** [comment]
That said, once everything is loaded and the user clicks "save and continue" it works great!

**Comment by huei90** [comment]
You sure have to wait everything load complete before submit button to prevent inconsistent value data.

**Comment by mcblum** [comment]
Is there a way to check whether all sub-components have loaded since the inputs are lately contained within them?

**Comment by huei90** [comment]
if your load is in AJAX, try using the promise to check the load state.
