### ISSUE TITLE
Add Custom Valid Message (error, success) for custom valdiation on html

### ISSUE THREAD

**Issue by agarciagan** [huei90/angular-validation#222]
Hi,
After generating a custom validation I had some problems providing a custom translated success/error message for it. 
The API help page (https://github.com/huei90/angular-validation/blob/master/API.md) shows an example for the email and required validations. 
In my case the validation was equalsPassword and equalsPassword-error-message and equalsPassword-success-message where not found by my app. I realized the name of the validaot is passed internally to lowercase, show after changing it to equals everything works.I think including another example on this page could be useful for more people.
This is my code:

-Definition of the field on the form using the translation plugin to customize the message:
`  <input  id="equals" ng-model="user.equals_password" name="equals" value=""  class="form-control input-md" type="password" validator="equals"
                                        validator-model="{{user.password}}" valid-method="blur" equals-error-message="{{ 'Password no coincide' | translate }}"  equals-success-message="{{ 'Password coincide' | translate }}"/>`

-Definition with default messages:
`$validationProvider
     .setExpression({
       equals: function(value, scope, element, attrs) {
         return value === attrs.validatorModel;
       }
     })
     .setDefaultMsg({
       equals: {
         error: 'Field is not equal to model',
         success: 'Equals to model'
       }
     })
     ;
`

**Comment by huei90** [comment]
Did you provide `validator="equals"` in your form input?

**Comment by agarciagan** [comment]
Yes, the whole input field is : 
` <input  id="equals" ng-model="user.equals_password" name="equals" value="" placeholder="{{ 'Confirmar contraseña' | translate }}" class="form-control input-md" type="password" validator="equals"
                                        validator-model="{{user.password}}" valid-method="blur" equals-error-message="{{ 'Password no coincide' | translate }}"  equals-success-message="{{ 'Password coincide' | translate }}"/>`

**Comment by huei90** [comment]
Thanks @agarciagan Do you mind creating a Pull Request to add the reminder about those validation name should be in lowercase?
