### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by rickerd** [huei90/angular-validation#226]
Hi All,

I'm using this module in my project and i made some validators too (i can submit them as an extra validation rule if you all want) but i'm having trouble with the validation of the form.

I want to use formName.$valid in order to check if a user can submit or not. This doesn't work so i looked around and i came across this;
`this.form = {
            checkValid: $validationProvider.checkValid
        }`

But... i don't want to set the everytime i use a form. I want the validator to have the logic to validate or invalidate a form, maybe with a directive or something?

Can you help me out, i don't know what to do next.

This is my controller.

      `angular.module('sim.validation.example', [
    'sim.validation'
     ])
    .controller('ExampleController', ['$injector', function ($injector) {
        this.dateFilledIn = new Date();

        var $validationProvider = $injector.get('$validation');

        this.form = {
            checkValid: $validationProvider.checkValid
        }
    }]);

    <button data-ng-disabled="!main.form.checkValid(validation)" class="btn btn-success btn-block btn-lg">Send</button>`

**Comment by huei90** [comment]
unfortunately, you have to do it one by one for every forms.

currently there is no any generic/specific button trigger enable through `checkValid`

**Comment by rickerd** [comment]
Hmm.. damnit.
Is there a way (maybe in your thoughts) on how to do this? And is this something other people also want?
I would like to help but i'm not a real pro (yet).

**Comment by huei90** [comment]
There is a directive works,

suppose you want to checkValid of the submit button, here's the element

```html
<button validation-submit="Form" ng-click="next()">Submit</button>
```

perhaps customize one directive for it, name as `checkValid`

```html
<button validation-submit="Form" ng-click="next()" check-valid="Form">Submit</button>
```

within the directive, it checks by using `$validationProvider.checkValid`, then you can use the directive everywhere.

hope this answer you.

**Comment by huei90** [comment]
> And is this something other people also want?

I would say, this is nice to have feature 🍻

**Comment by rickerd** [comment]
Okay, i will try and find a way to accomplish this.
Wish me luck :p

**Comment by rickerd** [comment]
@huei90 extra validations i worked on.
https://gist.github.com/rickerd/621b541736e7470c237e0f6f27180ea7

**Comment by huei90** [comment]
wow, it is cool! keep going.

**Comment by huei90** [comment]
btw, if you found the directive useful, you can contribute it to angular-validation 😄

**Comment by rickerd** [comment]
Noooooo, i'm working on it haha.
I'll make PR if it's done
