### ISSUE TITLE
Add id and selector for autogenerated message span

### ISSUE THREAD

**Issue by wujitouch** [huei90/angular-validation#228]
Currently, if you put an element after the input element, angular-validation will use that element to put the validator message instead of creating another element after that one.

Example:

`<div class="form-group">`
`    <label for="name">Name</name>`
`    <input type="text" id="name" validator="required" />`
`    <sub>your name</sub>`
`</div>`

In this case, validator will put the message in the sub element because of this in the provider:

/**
     * Add Message Element in config phase
     * When you need custom your messageElement 
     * NODE: this funtion & and `message-id` attribute, have similar purpose.
     * This function will help you add your `messageElement` automatically instead of pre-defined.
     * @param element
     */
    this.getMsgElement = function(element) {
      return element.next();
    };

It would be nice if it could generate and id for that element and get it based on that id instead of using element.next().

Thanks

**Comment by huei90** [comment]
this.getMsgElement allows user to customize his own html style.

So, I suggest you customize the method to achieve your requirement.

Hope this is fine.

**Comment by wujitouch** [comment]
I did but I felt it would be a good change to the original project. I'll submit a pull request when I have time.

On Sun, Jul 31, 2016 at 5:41 AM, Huei Tan < notifications@github.com [notifications@github.com] > wrote:
this.getMsgElement allows user to customize his own html style.

So, I suggest you customize the method to achieve your requirement.

Hope this is fine.

**Comment by huei90** [comment]
I would review your pr when it is ready.

To better understanding, your pr should contains detail about the test file, documentation and example, so then collaborators can discuss and decide whether to merge it.

Thanks a lot! Looking forward to your pull request :smile:
