### ISSUE TITLE
Conditional Required validation...

### ISSUE THREAD

**Issue by ab1303** [huei90/angular-validation#229]
Is there a way, I can do conditional validation e.g. "Conditional Required" validation.
My scenario is that I am building a directive and I want to turn on/off validation on inputs elements in that directive's html template based on a parameter.

**Comment by huei90** [comment]
Thanks for asking this question @ab1303 

Here's the discussion about the `condition` before,
https://github.com/huei90/angular-validation/issues/152

please have some time to read all the thread.

Please let me know if there is any other issues.

**Comment by ab1303** [comment]
Hi huei,
     I have gone through the thread, but I feel my case is a little different or I didn't understood the problem in that thread.
 
Let me elaborate my case.
I am making a directive named 

`<form>
<address require-validation="vm.isRequired"> </address>
<input type="submit" />
</form>`

Template of address is something like
`<input id="address1" validator="required" />
<input id="address2" validator="required"/>
<input id="address3" validator="required"/>`

Now if vm.isRequired=true, in that case angular-validation need to check for require validation on submit.
However if vm.isRequired=false in that case angular-validation need not check for validation.

**Comment by huei90** [comment]
@ab1303 here's the example of your condition `vm.isRequired`, try writing in your own code.

```html
<form name="Form">
    <label>Required</label>
    <input type="text" name="required" ng-model="form.required" validator="required">
    <button ng-click="submit(Form)">Submit</button>
</form>
<script>
// ...
$scope.submit = function (form) {
    // condition check
    if ( vm.isRequired /*your condition*/) {
        $validatorProvider.validate(form);
    }
}
// ...
</script>
```

hope this works .

**Comment by ab1303** [comment]
@huei90 

Thanks for your reply, I had looked at the above example before but unfortunately this is not what I am looking for.
I don't want to turn on/off validation of the form.
I am basically looking for a switch on a directive which will turn on/off validation on all the fields of that directive.
e.g. Address directive
In my case as I said in previous reply
```javascript
<form> 
	<employee>
		 <label>First Name</label>
		<input type="text" name="firstName" ng-model="vm.firstName" validator="required">
		<address require-validation="vm.isRequired"> </address> 
	</employee> 
	<button ng-click="submit(Form)">Submit</button>
</form>
```
The template of address directive is something link and I want below fields to be validated or not validated

```javascript
<input id="address1" validator="required" /> 
<input id="address2" validator="required"/> 
<input id="suburb" validator="required"/>
```

**Comment by huei90** [comment]
```
I don't want to turn on/off validation of the form. Form is always going to be validated
I am basically looking for a switch on a directive which will turn on/off validation on all the fields of that directive.
```

There is no way to do such thing in the current version of `angular-validation`.

**BUT**, would you mind helping to test the code below.

```html
<input id="address1" validator={{ vm.isRequired ? "required" : "" /> 
<input id="address2" validator={{ vm.isRequired ? "required" : ""/> 
<input id="suburb" validator={{ vm.isRequired ? "required" : ""/>
```

**Comment by huei90** [comment]
I believe the above solution works now because of this commit [Observe validator changes](https://github.com/huei90/angular-validation/commit/1a7f8f890118d6828873a5aaab928f6e04968534)
