### ISSUE TITLE
Constructor of Undefined

### ISSUE THREAD

**Issue by dsvvimal** [huei90/angular-validation#232]
i am getting "Cannot read property 'constructor' of undefined", when validating using button
below is the plnkr. 

could you please help me in fixing this?.

"https://plnkr.co/edit/908JHCQrxHQiDNpGxxWe?p=preview

**Comment by Nazanin1369** [comment]
I cannot reproduce the error you have mentioned. Can you give me the exact values you are entering in inputs

**Comment by dsvvimal** [comment]
Just click the button without entering any values and check the console.

**Comment by dmitry-dedukhin** [comment]
+1
The error appears when validation expression is a RegExp and check bellow is falsy

```
if (value !== undefined && value !== null)
```

In this case function checkValidation returns nothing.
