### ISSUE TITLE
How to avoid one field from the validation in a form

### ISSUE THREAD

**Issue by dharma-reddy** [huei90/angular-validation#233]
Hi,

I have 5 fields in form and out of that two fields are optional,Now I am not able to submit the form without entering those optional fields.
I have removed 'required' from those two optional fields.But, still i am not able to submit the form.

Please let me know what is the problem

Thanks,
Dharma

**Comment by huei90** [comment]
You should customize those two fields and allow them to accept null|undefined|"" value.
