### ISSUE TITLE
Validation based on multiple inputs.

### ISSUE THREAD

**Issue by xbenjii** [huei90/angular-validation#24]
Is this possible? I tried

``` js
$validationProvider
    .setExpression({
        matching: function(value, scope, element, attrs) {
            return scope.$parent.password === scope.$parent.passwordAgain;
        }
    })
    .setDefaultMsg({
        matching: {
            error: 'Passwords do not match.'
        }
    })
```

But it only works on the input that was last accessed.

**Comment by malykhinvi** [comment]
@huei90, the snippet you provided works just fine, if we enter *password* first. If I enter *passwordAgain* first and then *password*, the **matching** validator error will still present

**Comment by malykhinvi** [comment]
For now I use simple workaround. On password change I manually broadcast *submit* event for desired field(*passwordAgain* in the example above):
```javascript
function refreshConfirm(form) {
    $timeout(function () {
        $rootScope.$broadcast('confirmsubmit-' + form.confirm.validationId, 0);
    });
}
```

**Comment by huei90** [comment]
:+1:

**Comment by alexgoroshko** [comment]
@huei90 do you have another solution for @malykhinvi issue? I really don't want to get validation logic into controller.

**Comment by sujoysett** [comment]
thanks. spent a lot of time searching for this solution.

**Comment by huei90** [comment]
:+1: @sujoysett
