### ISSUE TITLE
How can i disable the submit button when form is invalid status ?

### ISSUE THREAD

**Issue by Github-Player** [huei90/angular-validation#244]
Hello huei,
How can i disable the submit button when form is invalid status ?
I expect use $watch feature and disable submit button if invalid, 
Which example should i use ?

My env is Angularjs 1.26

**Comment by huei90** [comment]
Sorry for the late replied.

`checkValid()` 

https://github.com/huei90/angular-validation/blob/master/API.md#check-form-whether-valid-return-true-if-valid-checkvalid-

Hope this is useful.
