### ISSUE TITLE
Validator number but not required

### ISSUE THREAD

**Issue by fplini** [huei90/angular-validation#251]
Hi all! I'm using this validation plugin but I have a problem. I have an input text (type=text and validator=number) but is not required for me. So if I try to submit the form no errors are showed but also no action is triggered.

Any idea? 
If I remove validator=number all works fine.

Thanks 
Fabrizio

**Comment by huei90** [comment]
try `validator="required, number"`

**Comment by fplini** [comment]
Hi and thanks for the reply. If I put "required" this means that the field is required but it isn't. So I can submit the form with the input value blank

**Comment by huei90** [comment]
if you are looking for using the `validator="number"` but doesn't want it to be `required`, please see this comment.
https://github.com/huei90/angular-validation/pull/241#issuecomment-255084600
