### ISSUE TITLE
Triggering toaster popup on validation error

### ISSUE THREAD

**Issue by jpthakkar** [huei90/angular-validation#252]
Hi, 

This is not really an issue; but I am looking forward for a suggestion to trigger toaster popup on validation error.  I am using below  configuration:

` $validationProvider.setErrorHTML(function (msg) {
            var html = '<span class=\'label label-danger\' translate>{{ \'{0}\' }}</span>'.replace('{0}', msg);
            return html;
        });`

Thank you in advance.

Best regards,
Jigar.

**Comment by huei90** [comment]
Hi @jpthakkar You can take this section as the example.
https://github.com/huei90/angular-validation#integrating-with-twitter-bootstrap

**Comment by jpthakkar** [comment]
Hi @huei90 , 

Thank your for your prompt response on this request. I shall try it and post a solution. 

Appreciate your help. 

Best regards

**Comment by huei90** [comment]
Cool, reopen this if you have any issue.

**Comment by jpthakkar** [comment]
Wow, this was easy.

here is solution: 

`angular.extend($validationProvider, {
            invalidCallback: function(element) {
                var msg = $(element).attr("required-error-message");
                logger.error(msg);
            }
   });`

HTML
`<input type="text" ng-model="vm.credential.username" translate translate-attr-placeholder="LOGIN.EMAIL_ADDRESS" validator="required" translate-attr-required-error-message="COMMON.FIELDSBLANK" valid-method="blur"/>`

@huei90  Thank you so much for your prompt help.

Best regards.

**Comment by huei90** [comment]
Nice! Awesome 🍻
