### ISSUE TITLE
Wiredep not picking angular-validation-rule.js by default

### ISSUE THREAD

**Issue by souravmondal93** [huei90/angular-validation#261]
Because of the missing dependencies in `bower.json` file, wiredep is not able to pick up 'angular-validation-rule.js' file. According to wiredep documentation, I am using the `override` property to overcome this problem. But, it will be better, if we can update the `bower.json` file.

#### Update bower.json file
```javascript
{
  "name": "angular-validation",
  "version": "1.4.2",
  "homepage": "https://github.com/huei90/angular-validation",
  "authors": [
    "huei90"
  ],
  "description": "Client-side Validation for AngularJS",
  "main": "dist/angular-validation.js",
  "keywords": [
    "angular",
    "angularjs",
    "validation",
    "angular validation",
    "validator",
    "client-side"
  ],
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    [
      "dist/angular-validation-rule.js"
    ]
  }
}
```
Notice the changes in `dependencies` key-value pair.
If needed, I can put a `pull-request` myself. Happy to contribute. :)

**Comment by huei90** [comment]
welcome PR 🍻
