### ISSUE TITLE
Cant use  validation-group

### ISSUE THREAD

**Issue by jejja** [huei90/angular-validation#264]
I get following console log when using validation-group:

angular-1.5.8.js:118 15:55:39.978::[global]> TypeError: Cannot read property '$setValidity' of undefined
    at b (http://localhost:9000/assets/javascripts/lib/angular-validation-1.4.2.min.js:1:4031)
    at http://localhost:9000/assets/javascripts/lib/angular-validation-1.4.2.min.js:1:5961
    at http://localhost:9000/assets/javascripts/lib/angular-1.5.8.js:131:20
    at m.$eval (http://localhost:9000/assets/javascripts/lib/angular-1.5.8.js:145:347)
    at m.$digest (http://localhost:9000/assets/javascripts/lib/angular-1.5.8.js:142:420)
    at m.$apply (http://localhost:9000/assets/javascripts/lib/angular-1.5.8.js:146:113)
    at HTMLButtonElement.<anonymous> (http://localhost:9000/assets/javascripts/lib/angular-1.5.8.js:276:247)
    at HTMLButtonElement.dispatch (http://localhost:9000/assets/javascripts/lib/jquery-2.1.4.min.js:3:6466)
    at HTMLButtonElement.r.handle (http://localhost:9000/assets/javascripts/lib/jquery-2.1.4.min.js:3:3241)

**Comment by huei90** [comment]
do you mind showing your code?

**Comment by jejja** [comment]
Well I can take some code... there is alot of fields I also had to rename some things:)
`<ng-form name="ctrl.form">
    <div class="radio" ng-repeat="num in numbers">
        <label>
                    <input type="radio"
                                name="number"
                                ng-model="ctrl.form.number"
                                ng-value="num"
                                validator="required"
                                valid-method="watch"
                                validation-group="contact">{{num}}
        </label>
      </div>
   <span id="contact"></span>
</ng-form>`

(I need to have the button for a reason outside the form... but this works without the group so)
        `<button type="button" class="btn btn-primary"
                ng-click="ctrl.validateForm(ctrl.form)">Send</button>`

And the validate-function:
`
        function validateForm(form) {
            $validation.validate(form)
            .success(function() {
            })
            .error(function() {
            });
        }
`

**Comment by huei90** [comment]
looks like you are using ng-repeat, hope this discussion is helpful
https://github.com/huei90/angular-validation/issues/63

and the demo code
https://github.com/huei90/angular-validation/commit/64b8eee0e98600ab1d3945dbe78dd651e71f6e0b

**Comment by jejja** [comment]
Hi.

No I didnt get that work. Ive added name="number{{$index}}". Since this are radiobuttons should they not have same name? With this {{ $index }} we get eunique name.

**Comment by jejja** [comment]
Hi!

I solved it. Since this are radiobuttons the name should be same. So I dont need to use the group-validation. Actually to make it look ok. I just needed to set a message-id and add a span where the error should be. :)

**Comment by huei90** [comment]
yes, if you see the demo `Form ($submit-only)` section, the checkbox 1 and 2 uses grouping 😄
