### ISSUE TITLE
Select Drop down issue when set default value from ng-model

### ISSUE THREAD

**Issue by kushal555** [huei90/angular-validation#267]
First, thank you very much for providing such a greate plugin. 
I am having an issue while I am using this plugin. 
In my form have a dropdown which auto set while form is open in edit mode using `ng-model` and also its not generating any validation message.

**Comment by kushal555** [comment]
Sorry, i got solution myself. 
Actually, i forgot the `name` attribute. So it's not validating the form even it has the value.

**Comment by huei90** [comment]
🍻
