### ISSUE TITLE
Can't access $http, $q... inside .setExpression()

### ISSUE THREAD

**Issue by bleuscyther** [huei90/angular-validation#35]
I cannot use $q like shown in the example unless i change the setup function to : 

``` javascript
 var setup = function (injector) {
                this.$injector = injector;
                this.$scope = this.$injector.get('$rootScope');
                this.$http = this.$injector.get('$http');
                this.$q = this.$injector.get('$q');
                this.$timeout = this.$injector.get('$timeout');        
            };
```

i had to add <b>this</b> in front of the variables....

**Comment by RichardSilveira** [comment]
Hi huei, can you post a sample to demonstrate how to create a custom validation using services like $http, i believe that issue isn´t a litlle confuse to some dev´s...

**Comment by huei90** [comment]
@RichardSilveira You can find out more here
https://github.com/huei90/angular-validation/blob/master/API.md#setup-a-new-validation-setexpression-setdefaultmsg-with-regexp-or-function-in-config-phase
