### ISSUE TITLE
How to validate checkboxes and radio buttons?

### ISSUE THREAD

**Issue by juan-mingo** [huei90/angular-validation#40]
I want to validate radio buttons and/or checkboxes as a group how should I do that?

**Comment by danicomas** [comment]
+1! very important!

**Comment by obender** [comment]
+1
Radio very important, Will try to Write my self and pull

**Comment by huei90** [comment]
Thanks @obender Need some surprise :+1:

**Comment by obender** [comment]
Hi,
I had added a pull request the Checkboxes and radio validation is working good,
I had added a pull request, https://github.com/huei90/angular-validation/pull/150

For now you can see how to use on radio on mine fork

**Comment by obender** [comment]
```
                <div>
                    <label>Type:</label>
                    <input type="radio" name="active" ng-model="form.active" value="yes" validator="required"
                           message-id="invalidActive"/>Active
                    <input type="radio" name="active" ng-model="form.active" value="no" validator="required"
                           message-id="invalidActive"/>Not Active
                    <div id="invalidActive"></div>
                </div>
```

**Comment by obender** [comment]
Currently working only for radio boxes group, not checkboxes, Will implement checkboxes some day :-)

**Comment by huei90** [comment]
Thanks @obender Look forward to see that.

**Comment by huei90** [comment]
We are working on this now and will be fixed it very soon.

**Comment by huei90** [comment]
Sorry guys for the late late late super late reply.

Checkbox valdiation is now ready :+1:
