### ISSUE TITLE
How do we do tooltips for error messages upon focusing?

### ISSUE THREAD

**Issue by httpete** [huei90/angular-validation#68]

**Comment by huei90** [comment]
Dear @httpete 
Reopen this issue if you have other question.

**Comment by danicomas** [comment]
An example that how I can open a bootstrap tooltip on error? @huei90

**Comment by danicomas** [comment]
@huei90 I want to do something like that (Example with jquery validate):

showErrors: function (errorMap, errorList) {
        this.defaultShowErrors();

        // destroy tooltips on valid elements                              
        $("." + this.settings.validClass).tooltip("destroy");
        $("." + this.settings.validClass).removeAttr("data-original-title");

        // add/update tooltips 
        for (var i = 0; i < errorList.length; i++) {
            var error = errorList[i];

            if ($("#" + error.element.id).attr("data-original-title")) {
                if (!($("#" + error.element.id).attr("data-original-title") == error.message)) {
                    $("#" + error.element.id).tooltip("destroy");
                    $("#" + error.element.id).tooltip({
                        container:body,
                        placement: "right",
                        template: '<div class="tooltip tooltip-error" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'
                    }).attr("data-original-title", error.message);
                    $("#" + error.element.id).tooltip("show");
                }
            }
            else {
                $("#" + error.element.id).tooltip({
                    container: body,
                    trigger: "focus",
                    placement: "right",
                    template: '<div class="tooltip tooltip-error" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'
                }).attr("data-original-title", error.message);
            }
        }
    }

**Comment by huei90** [comment]
Hi @danicomas Try using `message-id`

**Comment by danicomas** [comment]
Look at this: http://plnkr.co/edit/0tBZlijiwmDrSWcCP7U7?p=preview

The tooltip always appears. How can I solve this? @huei90

**Comment by huei90** [comment]
@danicomas You are able to disable success message shown by using `$validationProvider.showSuccessMessage = false; `

**Comment by danicomas** [comment]
@huei90 I don't want this. I want to show the tooltip when error appears.

**Comment by danicomas** [comment]
Other thing is that when you click on submit button no show errors! @huei90

**Comment by danicomas** [comment]
I have updated the plnkr.co: http://plnkr.co/edit/0tBZlijiwmDrSWcCP7U7?p=preview

I could do it but I think that best way is pass the message for the following callbacks:

```js
validCallback: function (element, message){ }
invalidCallback: function (element, message) { }
```

**Comment by huei90** [comment]
Great! Seems `validCallback` is works! Thanks for your update. :beers:
