### ISSUE TITLE
How to move the message position?

### ISSUE THREAD

**Issue by lvarayut** [huei90/angular-validation#69]
I created a form with `input-group-addon` class provided by Bootstrap, in order to embed an icon to the input, using the following code:

```html
<div class="input-group">
    <span class="input-group-addon"><i class="fa fa-child"></i></span>
    <input type="text" placeholder="name" data-ng-model="profile.name" validator="required" class="form-control">
    <span><label class="control-label has-success">It's Required</label></span>
</div>
```

When `angular-validation` added the message, it made the input field drop down one more line:

![screen shot 2557-12-20 at 3 00 59 pm](https://cloud.githubusercontent.com/assets/4281887/5514240/c079225e-8859-11e4-9ab1-4c4d4fdaaadc.png)

How to move the message out of the `div`, so that, it would not effect the height of the form?

**Comment by sweepy84** [comment]
Same problem here.... is there a workaround fix yet???

**Comment by huei90** [comment]
well, i think #70 can fix the issue.

**Comment by huei90** [comment]
@sweepy84 Sorry for the late reply.

Here's our solution.

https://github.com/huei90/angular-validation/pull/70

given message-id
```html
<label>Number</label>
<input type="text" name="number" ng-model="form.number" validator="number" message-id="message"/>
<span id="message"></span>
```
