### ISSUE TITLE
Is it possible to change the default valid-method?

### ISSUE THREAD

**Issue by mdmoura** [huei90/angular-validation#73]
Hello,

Is it possible to change the default valid-method to submit-only so it applies to all elements by default?

Thank You,
Miguel

**Comment by huei90** [comment]
Unfortunately, the default valid-method is `watch` now.

And there's no settings on the default valid-method right now.

**Comment by huei90** [comment]
Hi @mdmoura 

I suggest you on using [angular-validation-schema](https://github.com/thetutlage/angular-validation-schema) to set the `valid-method`

**Comment by huei90** [comment]
Close. Open it if you are further question.
