### ISSUE TITLE
Can't get the input focus event for page styling.

### ISSUE THREAD

**Issue by bmwertman** [huei90/angular-validation#77]
I have placeholders in my input fields that once the input gets focus I apply some CSS to have the placeholder position above it's respective input as a label(with a blue color). Once focus is lost and the info in the input is found as valid the label turns grey and remains above it's respective input. 

I want to use this in coordination with angular-validation to show error messages below each respective input. But the focus state previously used by my CSS labels seems to be getting intercepted by by the validator method. Any thoughts on a work around for this?

Thanks

**Comment by huei90** [comment]
Do you have a short DEMO for this?

Seems you need to modify the `setErrorHTML()`

you can search keyword `Custom the valid/invalid message style HTML in .config()`

in https://github.com/huei90/angular-validation/blob/master/API.md
