### ISSUE TITLE
Toggle has-error on parent form-group

### ISSUE THREAD

**Issue by tb** [huei90/angular-validation#80]
In Bootstrap you can make label, input and error message all have red text/outline if you set `.has-error` on parent container, typically `.form-group`

I was able to add in source code with:

    formGroupElem = element.parents('.form-group:first')
    formGroupElem.addClass('has-error');
    formGroupElem.removeClass('has-error');

I am doing it atm inside `invalidFunc` and `validFunc`.

Would you accept PR with it? Or would you suggest some other approach to address it? Maybe some callback that would be possible to set like `$validationProvider.setErrorHTML`?

**Comment by huei90** [comment]
@tb 

Your suggestion is correct.

And here's the reference we built before.

See if this is work to you.

https://github.com/huei90/angular-validation#integrating-with-twitter-bootstrap
