### ISSUE TITLE
Validation using schema

### ISSUE THREAD

**Issue by thetutlage** [huei90/angular-validation#83]
Hey there

I recently wrote a tiny provider , that adds schema based validation on angular-validation , have a look and see if you can add it as a reference to official docs

https://github.com/thetutlage/angular-validation-schema

**Comment by huei90** [comment]
Cool @thetutlage 

I love your idea.

You are welcome to add a link in README.md,
to direct to the schema link.

Waiting for your PR :beers:

**Comment by huei90** [comment]
nice
