### ISSUE TITLE
Positioning Error/Success message

### ISSUE THREAD

**Issue by roylee0704** [huei90/angular-validation#84]
Hi, greetings @huei90 , great library that you have written. :)

Yeah, there is a question from me, is there any way for me to freely point where should the error/success message be displayed rather than at  the  below of `<input>` tag ? 

---

The reason is because of the following issues faced:

![bootstrap add-ons + help-block message](https://cloud.githubusercontent.com/assets/8052198/3462871/d3f9be72-0232-11e4-98ee-973064a9a895.gif)

---

This is what I have tried based of your example:

```html
<div class="input-group">
    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
    <input name="chequeDateWatcher" message-id="chequeDateWatcher" ng-model="bla.chequeDateInput" validator="dateDDMMYY" valid-method="blur" autofocus>
</div>
<span id="chequeDateWatcher"></span>
```

**Comment by huei90** [comment]
@roylee0704 Did you get this error message by using `message-id` ?

**Comment by huei90** [comment]
Hey Malaysian @roylee0704

**Comment by roylee0704** [comment]
@huei90  You from Malaysia too ? :+1:   No I did not get any error message. I was expecting the error message would be somehow `injected` onto the span that I've just created.

**Comment by huei90** [comment]
Hey Malaysian Here :smile: 

I think you are having the same problem here.

https://github.com/huei90/angular-validation/issues/69

There's the implementation for you to try.

**Comment by roylee0704** [comment]
@huei90  What a Lighting-speed reply! :)  Alright I will take a look over it, by the way, is there any way to pass-in object/values onto the validator expression? So that I could do some dynamic validation? So far I have seen the validator-rule callback takes in `(value, scope, element, attrs)`. Should I just use what's available? If yes, what is the best way of passing in values than from the `<input>` model itself?

**Comment by huei90** [comment]
Well, currently there's no a better way to do that.

But I would suggest you to try

```html
<input type="text" name="dynamicInput" validator="dynamic_validator" dynamic-input="{{ dynamic }}"/>
```

You can try a validator name `dynamic_validator`

And use the variable `dynamic-input` to differentiate the validation in `dynamic_validator`.

**Comment by roylee0704** [comment]
So you mean I should just access any extra parameter via `attrs.dynamicInput` from the callback? :) 
```js
            dynamic_validator: function (value, scope, element, attrs) {

                  var fromNgModel = value;

                  var dynamicObj = attrs.dynamicInput;

                   // manipulation with dynamicObj

                 return true;
            },

```

Something like that?

**Comment by huei90** [comment]
yup

**Comment by roylee0704** [comment]
That's very awesome, I hope to see you soon @huei90. It's nice to see another Malaysian working very very well here.

**Comment by huei90** [comment]
Ha. Really nice to see people here.

Nice to meet you ^^

加油！哈哈

有問題在開 issue 咯！

**Comment by roylee0704** [comment]
okay ^^ ya, I have tried to pass in object via attrs, but no success.

**Comment by huei90** [comment]
a DEMO?

**Comment by crossRT** [comment]
Hi @hueitan and @roylee0704,
Good to know both of you're Malaysian too. I'm from P.J. =D

I know this topic is a bit old, but it still bothers me for a long time even if I follow this [guide](https://github.com/hueitan/angular-validation#integrating-with-twitter-bootstrap) and adding a `message-id` to integrate with bootstrap input-group.

So I wrote a small fix for this, maybe you can have a look.
Basically, I just extend these function to `$validationProvider`, to locate the proper element to inject validation message when `.input-group` is used.

```js
angular.extend($validationProvider, {
  addMsgElement: function(element) {
    if ($(element).parents('.input-group:first').length === 0) {
      return $(element).after('<span class="validation-message"></span>');
    } else {
      return $(element).parents('.input-group:first').after('<span class="validation-message"></span>');
    }
  },
  getMsgElement: function(element) {
    return $(element).parents('.form-group:first').find('.validation-message');
  }
})
```

Anyway, thanks for creating this awesome library! It's really helpful!

**Comment by hueitan** [comment]
🇲🇾
