### ISSUE TITLE
Validate only if has value

### ISSUE THREAD

**Issue by thetutlage** [huei90/angular-validation#86]
I have situation where i only want to check if the value is valid url if it has value. Which means it is not required but the value should be url if present.

So far it is not working for me 

##Input field

```html
<input type="text" ng-model="form.url" name="url" validator="url" valid-method="submit" url-error-message="It must be a url" url-success-message="">
```

**Comment by huei90** [comment]
It depends on the url validation type - regular expression

**Comment by thetutlage** [comment]
I am using the default url regular expression , the one served with validation rules

**Comment by huei90** [comment]
@thetutlage 

The default url regular expression is
```js
var pattern =  /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/;

// execute the null check
pattern.test(null); // => return false (means error)
```

So you have to modify the regex for url.

**Comment by thetutlage** [comment]
Okay make sense
