### ISSUE TITLE
[ENH/Change] validationSubmit and validationReset

### ISSUE THREAD

**Issue by mdmunir** [huei90/angular-validation#90]
- `validationSubmit` and `validationReset` should not required `ngClick`. It must only excecute `$validationProvider.validate(form)`.
- If value not provided, it must automatically detect `form` element from parent element.
`form = $(element).closest('form')`.

Overall... Thanks :+1:

**Comment by huei90** [comment]
```
validationSubmit and validationReset should not required ngClick. It must only excecute $validationProvider.validate(form).
```
I suppose that every form has their own purpose.
It should do something after validation. Therefore `ngClick` is needed.
The flow is: execute `$validationProvider.validate(form)` -> `ngClick`

```
If value not provided, it must automatically detect form element from parent element. form = $(element).closest('form').
```
I try it first XDD

**Comment by mdmunir** [comment]
> It **should** do something after validation. Therefore ngClick is needed.

**should** but not **must** :D. If want to do something after validation, set attribute `afterValidate` look more great for me.

**Comment by huei90** [comment]
May I know what's the case you are using now?

**Comment by mdmunir** [comment]
nothing... its just suggestion :D.

**Comment by huei90** [comment]
Then I'm going to close this issue.

In conclusion, 
why we need validation? We need to prevent invalid form submit. That's why we need a proper validation before the form submit.
