### ISSUE TITLE
Email field is validated although it's not required

### ISSUE THREAD

**Issue by zitniak** [huei90/angular-validation#91]
When I define validation of not required email field and put empty value there it reports 'This should be email'. But expected behavior should be when field is not required, empty field will be no validated
```html
<div>
    <label>Email</label>
    <input type="text" name="email" ng-model="form.email" validator="email">
</div>
```
Same for Url type field.

What do you think? How could I easy achieve validation of email field only when it's provided?

**Comment by huei90** [comment]
@zitniak 

I suppose that you are using the `rule.js` file

the email regex is `/^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/`

if you try this
```js
/^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/.test('');
// => return false (error)
```

Overall, you should change the regular expression of validator email.

**Comment by lopsided** [comment]
For reference, adding `|^$` to the end of the pattern fixes this. It simply says, "or match an empty string".

@huei90 what do you think about making this the default behaviour? It makes it a bit more flexible and what I think most people would expect (at least in my experience).

**Comment by huei90** [comment]
The email regex is set in `rule.js` as default used.
Anyone can change it on their own `rule.js`.

`rule.js` here just show some example only =)

**Comment by huei90** [comment]
Close. Open it if you are further question.

**Comment by lopsided** [comment]
In case anyone else stumbles across this, adding my fix in the regex does not actually fix this since the validator only passes to the regex if a value is provided. In my case I overrode the `email` rule in the `rule.js` file and replaced it with a simple callback so if there is no value it returns as valid. 

````
var emailRegex = // as original
...
email: function(value) {
            if (value) {
                return emailRegex.test(value);
            }
            return true;
        }
````
