### ISSUE TITLE
How can we change where success and error messages shows up?

### ISSUE THREAD

**Issue by 3lfist** [huei90/angular-validation#92]
Success and error messages are show up below the input field by default in an unstyled `<span>`. Obviously this won't work for some designers so is there a way to control where the messages show up?

**Comment by huei90** [comment]
Sure @3lfist 
You need to use `message-id`, it allow you to customise your own validation output
https://github.com/huei90/angular-validation/blob/master/API.md#use-a-custom-valid-message-

**Comment by huei90** [comment]
Close. Open it if you are further question.
