### ISSUE TITLE
email exists solution $http

### ISSUE THREAD

**Issue by wesley3523** [huei90/angular-validation#99]
Is there a way to do a $http request in my custom validation?

Thank i appreciate it

**Comment by huei90** [comment]
For your reference
https://github.com/huei90/angular-validation/issues/2

There're more references within the post.

**Comment by huei90** [comment]
Close issue. Open it if you have further question. Thanks :smile:

**Comment by RichardSilveira** [comment]
I have this "$http is not definwed" message error, isn´t possible to use services in module.config...How to solve that?

Thank´s

**Comment by huei90** [comment]
You can use `$httpProvider` in config.

**Comment by katytov** [comment]
@RichardSilveira, You can inject it like this :
var initInjector = angular.injector(['ng']);
var $http = initInjector.get('$http');
$http.post(...)
